(Dialog aventics_accuracy
  (Components
    (Label AccTitle) (Label AccRule) (Label AccSourceTitle) (CheckButton AccUseSelection)
    (Label AccFolderLabel) (InputPanel AccFolder) (PushButton AccBrowseButton)
    (Label AccOptionsTitle) (CheckButton AccRecursive) (CheckButton AccLatest)
    (Label AccTypesTitle) (CheckButton AccParts) (CheckButton AccAssemblies) (Label AccFound)
    (PushButton AccRunButton) (ProgressBar AccProgress) (Label AccProgressText)
    (Label AccResultsTitle) (Label AccSearchLabel) (InputPanel AccSearch) (CheckButton AccIssuesOnly)
    (Table AccTable) (Label AccSummary) (Label AccDetails)
    (PushButton AccOpenButton) (PushButton AccClearButton) (Label AccSpacer)
    (Label FooterStatus) (PushButton FooterCancelButton) (PushButton FullScreenButton)
    (PushButton ControlPanelButton) (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox v0.5.1 - Accuracy")
    (.Resizeable True) (.RememberSize True)
    (AccTitle.Label "Accuracy")
    (AccRule.Label "ABSOLUTE 0.001")
    (AccSourceTitle.Label "Source")
    (AccUseSelection.Label "Creo selection") (AccUseSelection.Set True)
    (AccFolderLabel.Label "Folder") (AccFolder.Columns 52)
    (AccBrowseButton.Label "Browse")
    (AccOptionsTitle.Label "Options")
    (AccRecursive.Label "Subfolders")
    (AccLatest.Label "Latest only") (AccLatest.Set True)
    (AccTypesTitle.Label "Models")
    (AccParts.Label "Parts") (AccParts.Set True)
    (AccAssemblies.Label "Assemblies") (AccAssemblies.Set True)
    (AccFound.Label "Selection source")
    (AccRunButton.Label "Check")
    (AccProgress.MinInteger 0) (AccProgress.MaxInteger 1) (AccProgress.Integer 0)
    (AccProgressText.Label "Ready")
    (AccResultsTitle.Label "Results") (AccSearchLabel.Label "Search") (AccSearch.Columns 26)
    (AccIssuesOnly.Label "Issues only")
    (AccTable.RowNames "empty")
    (AccTable.ColumnNames "Model" "Kind" "AccuracyType" "Accuracy" "Status")
    (AccTable.ColumnLabels "Model" "Kind" "Type" "Accuracy" "Status")
    (AccTable.ColumnWidths 30 12 13 13 11) (AccTable.VisibleRows 14)
    (AccTable.ShowGrid True) (AccTable.AttachLeft True) (AccTable.AttachRight True)
    (AccTable.AttachTop True) (AccTable.AttachBottom True)
    (AccSummary.Label "No results")
    (AccDetails.Label "Select a row for details.")
    (AccOpenButton.Label "Open") (AccClearButton.Label "Clear") (AccSpacer.Label "")
    (FooterStatus.Label "Ready") (FooterCancelButton.Label "Cancel")
    (FullScreenButton.Label "Full screen") (ControlPanelButton.Label "Home") (CloseButton.Label "Close")
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        (Grid (Rows 0 0 0 0 0 1 0 0 0) (Cols 1)
          (Grid (Rows 0) (Cols 0 1) AccTitle AccRule)
          (Grid (Rows 0) (Cols 0 0 0 1 0) AccSourceTitle AccUseSelection AccFolderLabel AccFolder AccBrowseButton)
          (Grid (Rows 0) (Cols 0 0 0 0 0 0 1) AccOptionsTitle AccRecursive AccLatest AccTypesTitle AccParts AccAssemblies AccFound)
          (Grid (Rows 0) (Cols 0 1 0) AccRunButton AccProgress AccProgressText)
          (Grid (Rows 0) (Cols 0 0 0 1) AccResultsTitle AccIssuesOnly AccSearchLabel AccSearch)
          AccTable AccSummary AccDetails
          (Grid (Rows 0) (Cols 0 0 1) AccOpenButton AccClearButton AccSpacer))
        (Grid (Rows 0) (Cols 1 0 0 0 0)
          FooterStatus FooterCancelButton FullScreenButton ControlPanelButton CloseButton)))))
