(Dialog aventics_toolbox
  (Components
    (Label OverviewTitle) (Label OverviewIntro)
    (Label OverviewQcTitle) (Label OverviewQcDesc)
    (PushButton OverviewRunAllButton) (Label OverviewRunAllStatus)
    (PushButton OverviewWeakButton) (PushButton OverviewAccButton) (Label OverviewQcSpacer)
    (Label OverviewAssemblyTitle) (Label OverviewAssemblyDesc)
    (PushButton OverviewInspButton) (PushButton OverviewInstButton) (Label OverviewAssemblySpacer)
    (Label OverviewSafety) (Label OverviewSpacer)
    (Label FooterStatus) (PushButton FooterCancelButton) (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox v0.5.2 - Control Panel")
    (.Resizeable True) (.RememberSize True)
    (OverviewTitle.Label "Aventics Toolbox")
    (OverviewIntro.Label "Creo engineering utilities")
    (OverviewQcTitle.Label "QUALITY CHECKS")
    (OverviewQcDesc.Label "Read-only model checks")
    (OverviewRunAllButton.Label "Run QC on selection")
    (OverviewRunAllStatus.Label "No QC run in this session")
    (OverviewWeakButton.Label "Weak Dimensions")
    (OverviewAccButton.Label "Accuracy")
    (OverviewQcSpacer.Label "")
    (OverviewAssemblyTitle.Label "ASSEMBLY TOOLS")
    (OverviewAssemblyDesc.Label "Active assembly required")
    (OverviewInspButton.Label "Inspection Builder")
    (OverviewInstButton.Label "Instance Builder")
    (OverviewAssemblySpacer.Label "")
    (OverviewSafety.Label "Assembly tools never auto-save")
    (OverviewSpacer.Label "")
    (FooterStatus.Label "Ready")
    (FooterCancelButton.Label "Cancel")
    (CloseButton.Label "Close")
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        (Grid (Rows 0 0 0 0 0 0 0 1) (Cols 1)
          (Grid (Rows 0) (Cols 0 1 0) OverviewTitle OverviewIntro CloseButton)
          (Grid (Rows 0) (Cols 0 1) OverviewQcTitle OverviewQcDesc)
          (Grid (Rows 0) (Cols 0 0 1) OverviewWeakButton OverviewAccButton OverviewQcSpacer)
          (Grid (Rows 0) (Cols 0 1) OverviewRunAllButton OverviewRunAllStatus)
          (Grid (Rows 0) (Cols 0 1) OverviewAssemblyTitle OverviewAssemblyDesc)
          (Grid (Rows 0) (Cols 0 0 1) OverviewInspButton OverviewInstButton OverviewAssemblySpacer)
          OverviewSafety
          OverviewSpacer)
        (Grid (Rows 0) (Cols 1 0) FooterStatus FooterCancelButton)))))
