(Dialog aventics_instance_builder
  (Components
    (Label InstTitle) (Label InstDescription) (Label InstTargetTitle) (Label InstActiveAsm)
    (Label InstInputTitle) (Label InstSourceTitle) (Label InstFolderLabel) (InputPanel InstFolder) (PushButton InstBrowseButton)
    (CheckButton InstRecursive) (CheckButton InstLatest) (Label InstFound)
    (Label InstCodesTitle) (TextArea InstCodes) (Label InstCodesHelp)
    (Label InstPlanTitle) (Label InstColumnsLabel) (InputPanel InstColumns)
    (Label InstGapLabel) (InputPanel InstGap) (PushButton InstPlanButton) (Label InstValidation)
    (Label InstBuildReviewTitle) (PushButton InstBuildButton) (ProgressBar InstProgress) (Label InstProgressText)
    (Label InstResultsTitle) (CheckButton InstUnresolvedOnly) (Label InstResultsSpacer)
    (Table InstTable) (Label InstSummary) (Label InstDetails)
    (PushButton InstExportButton) (PushButton InstClearButton) (Label InstSpacer)
    (Label FooterStatus) (PushButton FooterCancelButton) (PushButton FullScreenButton)
    (PushButton ControlPanelButton) (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox v0.5.0 - Instance Builder")
    (.Resizeable True) (.RememberSize True)
    (InstTitle.Label "Instance builder")
    (InstDescription.Label "Resolve requested codes and add matching models to the active assembly.")
    (InstTargetTitle.Label "Target assembly") (InstActiveAsm.Label "No active assembly")
    (InstInputTitle.Label "1. Input")
    (InstSourceTitle.Label "Search source") (InstFolderLabel.Label "Folder")
    (InstFolder.Columns 58) (InstBrowseButton.Label "Browse...")
    (InstRecursive.Label "Include subfolders")
    (InstLatest.Label "Latest version only") (InstLatest.Set True)
    (InstFound.Label "Choose the folder containing Creo parts and assemblies to search.")
    (InstCodesTitle.Label "Requested codes")
    (InstCodes.Rows 10) (InstCodes.Columns 64) (InstCodes.MinRows 6) (InstCodes.MaxLen 32767)
    (InstCodes.AttachLeft True) (InstCodes.AttachRight True)
    (InstCodesHelp.Label "Paste as many codes as needed. One per line; comma, semicolon, and tab are also accepted.")
    (InstPlanTitle.Label "2. Plan")
    (InstColumnsLabel.Label "Columns") (InstColumns.Columns 5)
    (InstGapLabel.Label "Gap (assembly units)") (InstGap.Columns 8)
    (InstPlanButton.Label "Plan positions")
    (InstValidation.Label "")
    (InstBuildReviewTitle.Label "3. Build and review")
    (InstBuildButton.Label "Find and add instances")
    (InstProgress.MinInteger 0) (InstProgress.MaxInteger 1) (InstProgress.Integer 0)
    (InstProgressText.Label "Ready")
    (InstResultsTitle.Label "Results")
    (InstUnresolvedOnly.Label "Unresolved only")
    (InstResultsSpacer.Label "")
    (InstTable.RowNames "empty")
    (InstTable.ColumnNames "Code" "Row" "Column" "Generic" "AddedModel" "Status")
    (InstTable.ColumnLabels "Requested code" "Row" "Column" "Generic" "Added model" "Status")
    (InstTable.ColumnWidths 24 7 7 24 25 12) (InstTable.VisibleRows 10)
    (InstTable.ShowGrid True) (InstTable.AttachLeft True) (InstTable.AttachRight True)
    (InstTable.AttachTop True) (InstTable.AttachBottom True)
    (InstSummary.Label "No plan")
    (InstDetails.Label "Missing instances leave their allocated position empty; assembly continues with the next requested position.")
    (InstExportButton.Label "Export CSV report")
    (InstClearButton.Label "Clear results") (InstSpacer.Label "")
    (FooterStatus.Label "Ready") (FooterCancelButton.Label "Cancel operation")
    (FullScreenButton.Label "Full screen") (ControlPanelButton.Label "Control Panel") (CloseButton.Label "Close")
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        (Grid (Rows 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0) (Cols 1)
          InstTitle InstDescription InstTargetTitle InstActiveAsm InstInputTitle InstSourceTitle
          (Grid (Rows 0) (Cols 0 1 0) InstFolderLabel InstFolder InstBrowseButton)
          (Grid (Rows 0) (Cols 0 0 1) InstRecursive InstLatest InstFound)
          InstCodesTitle InstCodes InstCodesHelp InstPlanTitle
          (Grid (Rows 0) (Cols 0 0 0 0 0 1) InstColumnsLabel InstColumns InstGapLabel InstGap InstPlanButton InstValidation)
          InstBuildReviewTitle
          (Grid (Rows 0) (Cols 0 1 0) InstBuildButton InstProgress InstProgressText)
          (Grid (Rows 0) (Cols 0 0 1) InstResultsTitle InstUnresolvedOnly InstResultsSpacer)
          InstTable InstSummary InstDetails
          (Grid (Rows 0) (Cols 0 0 1) InstExportButton InstClearButton InstSpacer))
        (Grid (Rows 0) (Cols 1 0 0 0 0)
          FooterStatus FooterCancelButton FullScreenButton ControlPanelButton CloseButton)))))
