(Dialog aventics_toolbox
  (Components
    (Label OverviewTitle) (Label OverviewIntro)
    (Label OverviewQcTitle) (Label OverviewQcDesc)
    (PushButton OverviewRunAllButton) (Label OverviewRunAllStatus)
    (PushButton OverviewWeakButton) (PushButton OverviewAccButton) (Label OverviewQcSpacer)
    (Label OverviewAssemblyTitle) (Label OverviewAssemblyDesc)
    (PushButton OverviewInspButton) (PushButton OverviewInstButton) (Label OverviewAssemblySpacer)
    (Label OverviewSafety) (Label OverviewSpacer)
    (Label FooterStatus) (PushButton FooterCancelButton) (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox v0.5.2 - Control Panel")
    (.Resizeable True) (.RememberSize True)
    (.TopOffset 10) (.BottomOffset 10) (.LeftOffset 10) (.RightOffset 10)
    (OverviewTitle.Label "Aventics Toolbox")
    (OverviewTitle.TopOffset 6) (OverviewTitle.BottomOffset 6) (OverviewTitle.LeftOffset 4)
    (OverviewIntro.Label "Creo engineering utilities")
    (OverviewIntro.TopOffset 6) (OverviewIntro.BottomOffset 6) (OverviewIntro.LeftOffset 8)
    (OverviewQcTitle.Label "QUALITY CHECKS")
    (OverviewQcTitle.TopOffset 12) (OverviewQcTitle.BottomOffset 4) (OverviewQcTitle.LeftOffset 4)
    (OverviewQcDesc.Label "Read-only model checks")
    (OverviewQcDesc.TopOffset 12) (OverviewQcDesc.BottomOffset 4) (OverviewQcDesc.LeftOffset 8)
    (OverviewRunAllButton.Label "Run QC on selection")
    (OverviewRunAllButton.TopOffset 7) (OverviewRunAllButton.BottomOffset 7)
    (OverviewRunAllButton.LeftOffset 4) (OverviewRunAllButton.RightOffset 6)
    (OverviewRunAllStatus.Label "No QC run in this session")
    (OverviewRunAllStatus.TopOffset 7) (OverviewRunAllStatus.BottomOffset 7) (OverviewRunAllStatus.LeftOffset 8)
    (OverviewWeakButton.Label "Weak Dimensions")
    (OverviewAccButton.Label "Accuracy")
    (OverviewWeakButton.TopOffset 6) (OverviewWeakButton.BottomOffset 6) (OverviewWeakButton.LeftOffset 4) (OverviewWeakButton.RightOffset 4)
    (OverviewAccButton.TopOffset 6) (OverviewAccButton.BottomOffset 6) (OverviewAccButton.LeftOffset 4) (OverviewAccButton.RightOffset 4)
    (OverviewQcSpacer.Label "")
    (OverviewAssemblyTitle.Label "ASSEMBLY TOOLS")
    (OverviewAssemblyTitle.TopOffset 12) (OverviewAssemblyTitle.BottomOffset 4) (OverviewAssemblyTitle.LeftOffset 4)
    (OverviewAssemblyDesc.Label "Active assembly required")
    (OverviewAssemblyDesc.TopOffset 12) (OverviewAssemblyDesc.BottomOffset 4) (OverviewAssemblyDesc.LeftOffset 8)
    (OverviewInspButton.Label "Inspection Builder")
    (OverviewInstButton.Label "Instance Builder")
    (OverviewInspButton.TopOffset 6) (OverviewInspButton.BottomOffset 6) (OverviewInspButton.LeftOffset 4) (OverviewInspButton.RightOffset 4)
    (OverviewInstButton.TopOffset 6) (OverviewInstButton.BottomOffset 6) (OverviewInstButton.LeftOffset 4) (OverviewInstButton.RightOffset 4)
    (OverviewAssemblySpacer.Label "")
    (OverviewSafety.Label "Assembly tools never auto-save")
    (OverviewSafety.TopOffset 12) (OverviewSafety.BottomOffset 8) (OverviewSafety.LeftOffset 4)
    (OverviewSpacer.Label "")
    (FooterStatus.Label "Ready")
    (FooterStatus.TopOffset 8) (FooterStatus.BottomOffset 2) (FooterStatus.LeftOffset 4)
    (FooterCancelButton.Label "Cancel")
    (FooterCancelButton.TopOffset 6) (FooterCancelButton.BottomOffset 2) (FooterCancelButton.LeftOffset 6)
    (CloseButton.Label "") (CloseButton.Bitmap "cl_cancel")
    (CloseButton.HelpText "Close") (CloseButton.ButtonStyle 3)
    (CloseButton.TopOffset 4) (CloseButton.BottomOffset 4) (CloseButton.LeftOffset 6) (CloseButton.RightOffset 4)
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        (Grid (Rows 0 0 0 0 0 0 0 1) (Cols 1)
          (Grid (Rows 0) (Cols 0 1 0) OverviewTitle OverviewIntro CloseButton)
          (Grid (Rows 0) (Cols 0 1) OverviewQcTitle OverviewQcDesc)
          (Grid (Rows 0) (Cols 0 0 1) OverviewWeakButton OverviewAccButton OverviewQcSpacer)
          (Grid (Rows 0) (Cols 0 1) OverviewRunAllButton OverviewRunAllStatus)
          (Grid (Rows 0) (Cols 0 1) OverviewAssemblyTitle OverviewAssemblyDesc)
          (Grid (Rows 0) (Cols 0 0 1) OverviewInspButton OverviewInstButton OverviewAssemblySpacer)
          OverviewSafety
          OverviewSpacer)
        (Grid (Rows 0) (Cols 1 0) FooterStatus FooterCancelButton)))))
