(Dialog aventics_accuracy
  (Components
    (Label AccTitle) (Label AccRule) (Label AccSourceTitle) (CheckButton AccUseSelection)
    (Label AccFolderLabel) (InputPanel AccFolder) (PushButton AccBrowseButton)
    (Label AccOptionsTitle) (CheckButton AccRecursive) (CheckButton AccLatest)
    (Label AccTypesTitle) (CheckButton AccParts) (CheckButton AccAssemblies) (Label AccFound)
    (PushButton AccRunButton) (ProgressBar AccProgress) (Label AccProgressText)
    (Label AccResultsTitle) (Label AccSearchLabel) (InputPanel AccSearch) (CheckButton AccIssuesOnly)
    (Table AccTable) (Label AccSummary) (Label AccDetails)
    (PushButton AccOpenButton) (PushButton AccClearButton) (Label AccSpacer)
    (Label FooterStatus) (PushButton FooterCancelButton) (PushButton FullScreenButton)
    (PushButton ControlPanelButton) (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox v0.5.2 - Accuracy")
    (.Resizeable True) (.RememberSize True)
    (.TopOffset 8) (.BottomOffset 8) (.LeftOffset 8) (.RightOffset 8)
    (AccTitle.Label "Accuracy")
    (AccTitle.TopOffset 5) (AccTitle.BottomOffset 5) (AccTitle.LeftOffset 4)
    (AccRule.Label "Requirement: ABSOLUTE = 0.001")
    (AccRule.TopOffset 5) (AccRule.BottomOffset 5) (AccRule.LeftOffset 8)
    (AccSourceTitle.Label "SOURCE")
    (AccSourceTitle.TopOffset 10) (AccSourceTitle.BottomOffset 4) (AccSourceTitle.LeftOffset 4)
    (AccUseSelection.Label "Use selected models") (AccUseSelection.Set True)
    (AccUseSelection.TopOffset 4) (AccUseSelection.BottomOffset 4) (AccUseSelection.LeftOffset 6) (AccUseSelection.RightOffset 6)
    (AccFolderLabel.Label "Folder")
    (AccFolderLabel.TopOffset 4) (AccFolderLabel.BottomOffset 4) (AccFolderLabel.LeftOffset 6)
    (AccFolder.Columns 52)
    (AccFolder.TopOffset 4) (AccFolder.BottomOffset 4) (AccFolder.LeftOffset 4) (AccFolder.RightOffset 4)
    (AccBrowseButton.Label "Browse") (AccBrowseButton.ButtonStyle 3) (AccBrowseButton.HelpText "Choose a source folder")
    (AccBrowseButton.TopOffset 4) (AccBrowseButton.BottomOffset 4) (AccBrowseButton.LeftOffset 4) (AccBrowseButton.RightOffset 4)
    (AccOptionsTitle.Label "Folder options")
    (AccOptionsTitle.TopOffset 5) (AccOptionsTitle.BottomOffset 5) (AccOptionsTitle.LeftOffset 4)
    (AccRecursive.Label "Include subfolders")
    (AccRecursive.TopOffset 4) (AccRecursive.BottomOffset 4) (AccRecursive.LeftOffset 6) (AccRecursive.RightOffset 6)
    (AccLatest.Label "Latest only") (AccLatest.Set True)
    (AccLatest.TopOffset 4) (AccLatest.BottomOffset 4) (AccLatest.LeftOffset 6) (AccLatest.RightOffset 6)
    (AccTypesTitle.Label "MODEL TYPES")
    (AccTypesTitle.TopOffset 6) (AccTypesTitle.BottomOffset 5) (AccTypesTitle.LeftOffset 4)
    (AccParts.Label "Parts") (AccParts.Set True)
    (AccParts.TopOffset 4) (AccParts.BottomOffset 4) (AccParts.LeftOffset 6) (AccParts.RightOffset 6)
    (AccAssemblies.Label "Assemblies") (AccAssemblies.Set True)
    (AccAssemblies.TopOffset 4) (AccAssemblies.BottomOffset 4) (AccAssemblies.LeftOffset 6) (AccAssemblies.RightOffset 6)
    (AccFound.Label "Using selected models")
    (AccFound.TopOffset 4) (AccFound.BottomOffset 4) (AccFound.LeftOffset 8)
    (AccRunButton.Label "Check")
    (AccRunButton.TopOffset 8) (AccRunButton.BottomOffset 8) (AccRunButton.LeftOffset 4) (AccRunButton.RightOffset 6)
    (AccProgress.MinInteger 0) (AccProgress.MaxInteger 1) (AccProgress.Integer 0)
    (AccProgress.TopOffset 8) (AccProgress.BottomOffset 8) (AccProgress.LeftOffset 4) (AccProgress.RightOffset 4)
    (AccProgressText.Label "Ready")
    (AccProgressText.TopOffset 8) (AccProgressText.BottomOffset 8) (AccProgressText.LeftOffset 6)
    (AccResultsTitle.Label "RESULTS")
    (AccResultsTitle.TopOffset 10) (AccResultsTitle.BottomOffset 5) (AccResultsTitle.LeftOffset 4)
    (AccSearchLabel.Label "Search")
    (AccSearchLabel.TopOffset 8) (AccSearchLabel.BottomOffset 5) (AccSearchLabel.LeftOffset 6)
    (AccSearch.Columns 26)
    (AccSearch.TopOffset 6) (AccSearch.BottomOffset 5) (AccSearch.LeftOffset 4) (AccSearch.RightOffset 4)
    (AccIssuesOnly.Label "Issues only")
    (AccIssuesOnly.TopOffset 7) (AccIssuesOnly.BottomOffset 5) (AccIssuesOnly.LeftOffset 6) (AccIssuesOnly.RightOffset 6)
    (AccTable.RowNames "empty")
    (AccTable.ColumnNames "Model" "Kind" "AccuracyType" "Accuracy" "Status")
    (AccTable.ColumnLabels "Model" "Kind" "Type" "Accuracy" "Status")
    (AccTable.ColumnWidths 30 12 13 13 11) (AccTable.VisibleRows 15)
    (AccTable.ShowGrid True) (AccTable.AttachLeft True) (AccTable.AttachRight True)
    (AccTable.AttachTop True) (AccTable.AttachBottom True)
    (AccTable.TopOffset 5) (AccTable.BottomOffset 6) (AccTable.LeftOffset 4) (AccTable.RightOffset 4)
    (AccSummary.Label "No results")
    (AccSummary.TopOffset 8) (AccSummary.BottomOffset 5) (AccSummary.LeftOffset 8)
    (AccDetails.Label "Select a result for source and technical details.")
    (AccDetails.TopOffset 5) (AccDetails.BottomOffset 5) (AccDetails.LeftOffset 4)
    (AccOpenButton.Label "Open") (AccOpenButton.ButtonStyle 3)
    (AccClearButton.Label "Clear") (AccClearButton.ButtonStyle 3)
    (AccOpenButton.TopOffset 4) (AccOpenButton.BottomOffset 4) (AccOpenButton.LeftOffset 4) (AccOpenButton.RightOffset 4)
    (AccClearButton.TopOffset 4) (AccClearButton.BottomOffset 4) (AccClearButton.LeftOffset 4) (AccClearButton.RightOffset 4)
    (AccSpacer.Label "")
    (FooterStatus.Label "Ready")
    (FooterStatus.TopOffset 8) (FooterStatus.BottomOffset 2) (FooterStatus.LeftOffset 4)
    (FooterCancelButton.Label "Cancel")
    (FooterCancelButton.TopOffset 6) (FooterCancelButton.BottomOffset 2) (FooterCancelButton.LeftOffset 6)
    (FullScreenButton.Label "Maximize / restore") (FullScreenButton.ButtonStyle 3)
    (FullScreenButton.HelpText "Maximize or restore this tool window")
    (FullScreenButton.TopOffset 4) (FullScreenButton.BottomOffset 4) (FullScreenButton.LeftOffset 4) (FullScreenButton.RightOffset 4)
    (ControlPanelButton.Label "Toolbox") (ControlPanelButton.ButtonStyle 3)
    (ControlPanelButton.HelpText "Return to the Control Panel")
    (ControlPanelButton.TopOffset 4) (ControlPanelButton.BottomOffset 4) (ControlPanelButton.LeftOffset 4) (ControlPanelButton.RightOffset 4)
    (CloseButton.Label "") (CloseButton.Bitmap "cl_cancel")
    (CloseButton.HelpText "Close") (CloseButton.ButtonStyle 3)
    (CloseButton.TopOffset 4) (CloseButton.BottomOffset 4) (CloseButton.LeftOffset 4) (CloseButton.RightOffset 4)
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        (Grid (Rows 0 0 0 0 0 0 1 0 0) (Cols 1)
          (Grid (Rows 0) (Cols 0 0 1 0 0) ControlPanelButton AccTitle AccRule FullScreenButton CloseButton)
          (Grid (Rows 0) (Cols 0 0 0 1 0) AccSourceTitle AccUseSelection AccFolderLabel AccFolder AccBrowseButton)
          (Grid (Rows 0) (Cols 0 0 0 1) AccOptionsTitle AccRecursive AccLatest AccFound)
          (Grid (Rows 0) (Cols 0 0 0) AccTypesTitle AccParts AccAssemblies)
          (Grid (Rows 0) (Cols 0 1 0) AccRunButton AccProgress AccProgressText)
          (Grid (Rows 0) (Cols 0 1 0 0 0) AccResultsTitle AccSummary AccIssuesOnly AccSearchLabel AccSearch)
          AccTable
          AccDetails
          (Grid (Rows 0) (Cols 0 1 0) AccOpenButton AccSpacer AccClearButton))
        (Grid (Rows 0) (Cols 1 0) FooterStatus FooterCancelButton)))))
