(Dialog aventics_toolbox
  (Components
    (Label OverviewTitle) (Label OverviewIntro)
    (Label OverviewQcTitle) (Label OverviewQcDesc)
    (PushButton OverviewRunAllButton) (Label OverviewRunAllStatus)
    (PushButton OverviewWeakButton) (PushButton OverviewAccButton) (Label OverviewQcSpacer)
    (Label OverviewAssemblyTitle) (Label OverviewAssemblyDesc)
    (PushButton OverviewInspButton) (PushButton OverviewInstButton) (Label OverviewAssemblySpacer)
    (Label OverviewSafety) (Label OverviewSpacer)
    (Label FooterStatus) (PushButton FooterCancelButton) (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox - v0.5.0 | Control Panel")
    (.Resizeable True) (.RememberSize True)
    (OverviewTitle.Label "Aventics Toolbox Control Panel")
    (OverviewIntro.Label "Open each engineering tool in its own Creo GUI.")
    (OverviewQcTitle.Label "Quality control - read-only")
    (OverviewQcDesc.Label "Weak Dimensions applies to parts; Accuracy applies to parts and assemblies.")
    (OverviewRunAllButton.Label "Run all QC on Creo selection")
    (OverviewRunAllStatus.Label "Ready. Open a QC tool from the Control Panel to review results.")
    (OverviewWeakButton.Label "Weak Dimensions")
    (OverviewAccButton.Label "Accuracy")
    (OverviewQcSpacer.Label "")
    (OverviewAssemblyTitle.Label "Assembly tools")
    (OverviewAssemblyDesc.Label "Inspection and Instance Builder add unconstrained components to the active assembly.")
    (OverviewInspButton.Label "Inspection")
    (OverviewInstButton.Label "Instance Builder")
    (OverviewAssemblySpacer.Label "")
    (OverviewSafety.Label "Assembly tools never save the active assembly automatically.")
    (OverviewSpacer.Label "")
    (FooterStatus.Label "Ready")
    (FooterCancelButton.Label "Cancel operation")
    (CloseButton.Label "Close")
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        (Grid (Rows 0 0 0 0 0 0 0 0 0 0 0 1) (Cols 1)
          OverviewTitle OverviewIntro OverviewQcTitle OverviewQcDesc
          OverviewRunAllButton OverviewRunAllStatus
          (Grid (Rows 0) (Cols 0 0 1) OverviewWeakButton OverviewAccButton OverviewQcSpacer)
          OverviewAssemblyTitle OverviewAssemblyDesc
          (Grid (Rows 0) (Cols 0 0 1) OverviewInspButton OverviewInstButton OverviewAssemblySpacer)
          OverviewSafety OverviewSpacer)
        (Grid (Rows 0) (Cols 1 0 0) FooterStatus FooterCancelButton CloseButton)))))
