(Dialog aventics_instance_builder
  (Components
    (Label InstTitle) (Label InstDescription) (Label InstTargetTitle) (Label InstActiveAsm)
    (Label InstInputTitle) (Label InstSourceTitle) (Label InstFolderLabel) (InputPanel InstFolder) (PushButton InstBrowseButton)
    (CheckButton InstRecursive) (CheckButton InstLatest) (Label InstFound)
    (Label InstCodesTitle) (TextArea InstCodes) (Label InstCodesHelp)
    (Label InstPlanTitle) (Label InstColumnsLabel) (InputPanel InstColumns)
    (Label InstGapLabel) (InputPanel InstGap) (PushButton InstPlanButton) (Label InstValidation)
    (Label InstBuildReviewTitle) (PushButton InstBuildButton) (ProgressBar InstProgress) (Label InstProgressText)
    (Label InstResultsTitle) (CheckButton InstUnresolvedOnly) (Label InstResultsSpacer)
    (Table InstTable) (Label InstSummary) (Label InstDetails)
    (PushButton InstExportButton) (PushButton InstClearButton) (Label InstSpacer)
    (Label FooterStatus) (PushButton FooterCancelButton) (PushButton FullScreenButton)
    (PushButton ControlPanelButton) (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox v0.5.1 - Instance Builder")
    (.Resizeable True) (.RememberSize True)
    (InstTitle.Label "Instance builder")
    (InstDescription.Label "Exact code placement")
    (InstTargetTitle.Label "Target") (InstActiveAsm.Label "No active assembly")
    (InstInputTitle.Label "Input")
    (InstSourceTitle.Label "Source") (InstFolderLabel.Label "Folder")
    (InstFolder.Columns 52) (InstBrowseButton.Label "Browse")
    (InstRecursive.Label "Subfolders")
    (InstLatest.Label "Latest only") (InstLatest.Set True)
    (InstFound.Label "Choose source folder")
    (InstCodesTitle.Label "Codes")
    (InstCodes.Rows 10) (InstCodes.Columns 64) (InstCodes.MinRows 6) (InstCodes.MaxLen 32767)
    (InstCodes.AttachLeft True) (InstCodes.AttachRight True)
    (InstCodesHelp.Label "One per line, comma, semicolon, or tab")
    (InstPlanTitle.Label "Plan")
    (InstColumnsLabel.Label "Columns") (InstColumns.Columns 5)
    (InstGapLabel.Label "Gap") (InstGap.Columns 8)
    (InstPlanButton.Label "Plan")
    (InstValidation.Label "")
    (InstBuildReviewTitle.Label "Build")
    (InstBuildButton.Label "Build")
    (InstProgress.MinInteger 0) (InstProgress.MaxInteger 1) (InstProgress.Integer 0)
    (InstProgressText.Label "Ready")
    (InstResultsTitle.Label "Results")
    (InstUnresolvedOnly.Label "Unresolved only")
    (InstResultsSpacer.Label "")
    (InstTable.RowNames "empty")
    (InstTable.ColumnNames "Code" "Row" "Column" "Generic" "AddedModel" "Status")
    (InstTable.ColumnLabels "Code" "Row" "Col" "Generic" "Added model" "Status")
    (InstTable.ColumnWidths 24 7 7 24 25 12) (InstTable.VisibleRows 12)
    (InstTable.ShowGrid True) (InstTable.AttachLeft True) (InstTable.AttachRight True)
    (InstTable.AttachTop True) (InstTable.AttachBottom True)
    (InstSummary.Label "No plan")
    (InstDetails.Label "Missing codes keep their grid position.")
    (InstExportButton.Label "Export CSV")
    (InstClearButton.Label "Clear") (InstSpacer.Label "")
    (FooterStatus.Label "Ready") (FooterCancelButton.Label "Cancel")
    (FullScreenButton.Label "Full screen") (ControlPanelButton.Label "Home") (CloseButton.Label "Close")
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        (Grid (Rows 0 0 0 0 0 0 0 0 0 1 0 0 0) (Cols 1)
          (Grid (Rows 0) (Cols 0 1) InstTitle InstDescription)
          (Grid (Rows 0) (Cols 0 1) InstTargetTitle InstActiveAsm)
          (Grid (Rows 0) (Cols 0 0 0 1 0) InstInputTitle InstSourceTitle InstFolderLabel InstFolder InstBrowseButton)
          (Grid (Rows 0) (Cols 0 0 1) InstRecursive InstLatest InstFound)
          (Grid (Rows 0) (Cols 0 1) InstCodesTitle InstCodesHelp)
          InstCodes
          (Grid (Rows 0) (Cols 0 0 0 0 0 0 1) InstPlanTitle InstColumnsLabel InstColumns InstGapLabel InstGap InstPlanButton InstValidation)
          (Grid (Rows 0) (Cols 0 0 1 0) InstBuildReviewTitle InstBuildButton InstProgress InstProgressText)
          (Grid (Rows 0) (Cols 0 0 1) InstResultsTitle InstUnresolvedOnly InstResultsSpacer)
          InstTable InstSummary InstDetails
          (Grid (Rows 0) (Cols 0 0 1) InstExportButton InstClearButton InstSpacer))
        (Grid (Rows 0) (Cols 1 0 0 0 0)
          FooterStatus FooterCancelButton FullScreenButton ControlPanelButton CloseButton)))))
