(Dialog aventics_instance_builder
  (Components
    (Label InstTitle) (Label InstDescription) (Label InstTargetTitle) (Label InstActiveAsm)
    (Label InstInputTitle) (Label InstSourceTitle) (Label InstFolderLabel) (InputPanel InstFolder) (PushButton InstBrowseButton)
    (CheckButton InstRecursive) (CheckButton InstLatest) (Label InstFound)
    (Label InstCodesTitle) (TextArea InstCodes) (Label InstCodesHelp)
    (Label InstPlanTitle) (Label InstColumnsLabel) (InputPanel InstColumns)
    (Label InstGapLabel) (InputPanel InstGap) (PushButton InstPlanButton) (Label InstValidation)
    (Label InstBuildReviewTitle) (PushButton InstBuildButton) (ProgressBar InstProgress) (Label InstProgressText)
    (Label InstResultsTitle) (CheckButton InstUnresolvedOnly) (Label InstResultsSpacer)
    (Table InstTable) (Label InstSummary) (Label InstDetails)
    (PushButton InstExportButton) (PushButton InstClearButton) (Label InstSpacer)
    (Label FooterStatus) (PushButton FooterCancelButton) (PushButton FullScreenButton)
    (PushButton ControlPanelButton) (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox v0.5.2 - Instance Builder")
    (.Resizeable True) (.RememberSize True)
    (.TopOffset 8) (.BottomOffset 8) (.LeftOffset 8) (.RightOffset 8)
    (InstTitle.Label "Instance Builder")
    (InstTitle.TopOffset 5) (InstTitle.BottomOffset 5) (InstTitle.LeftOffset 4)
    (InstDescription.Label "Exact requested-instance placement")
    (InstDescription.TopOffset 5) (InstDescription.BottomOffset 5) (InstDescription.LeftOffset 8)
    (InstTargetTitle.Label "TARGET")
    (InstTargetTitle.TopOffset 9) (InstTargetTitle.BottomOffset 5) (InstTargetTitle.LeftOffset 4)
    (InstActiveAsm.Label "No active assembly")
    (InstActiveAsm.TopOffset 9) (InstActiveAsm.BottomOffset 5) (InstActiveAsm.LeftOffset 8)
    (InstInputTitle.Label "1 SOURCE")
    (InstInputTitle.TopOffset 10) (InstInputTitle.BottomOffset 5) (InstInputTitle.LeftOffset 4)
    (InstSourceTitle.Label "Search")
    (InstSourceTitle.TopOffset 5) (InstSourceTitle.BottomOffset 5) (InstSourceTitle.LeftOffset 6)
    (InstFolderLabel.Label "Folder")
    (InstFolderLabel.TopOffset 5) (InstFolderLabel.BottomOffset 5) (InstFolderLabel.LeftOffset 6)
    (InstFolder.Columns 52)
    (InstFolder.TopOffset 4) (InstFolder.BottomOffset 4) (InstFolder.LeftOffset 4) (InstFolder.RightOffset 4)
    (InstBrowseButton.Label "Browse") (InstBrowseButton.ButtonStyle 3) (InstBrowseButton.HelpText "Choose a source folder")
    (InstBrowseButton.TopOffset 4) (InstBrowseButton.BottomOffset 4) (InstBrowseButton.LeftOffset 4) (InstBrowseButton.RightOffset 4)
    (InstRecursive.Label "Include subfolders")
    (InstRecursive.TopOffset 4) (InstRecursive.BottomOffset 4) (InstRecursive.LeftOffset 4) (InstRecursive.RightOffset 6)
    (InstLatest.Label "Latest only") (InstLatest.Set True)
    (InstLatest.TopOffset 4) (InstLatest.BottomOffset 4) (InstLatest.LeftOffset 4) (InstLatest.RightOffset 6)
    (InstFound.Label "Choose a source folder")
    (InstFound.TopOffset 4) (InstFound.BottomOffset 6) (InstFound.LeftOffset 8)
    (InstCodesTitle.Label "2 REQUESTED CODES")
    (InstCodesTitle.TopOffset 10) (InstCodesTitle.BottomOffset 5) (InstCodesTitle.LeftOffset 4)
    (InstCodes.Rows 10) (InstCodes.Columns 64) (InstCodes.MinRows 6) (InstCodes.MaxLen 32767)
    (InstCodes.AttachLeft True) (InstCodes.AttachRight True)
    (InstCodes.TopOffset 5) (InstCodes.BottomOffset 6) (InstCodes.LeftOffset 4) (InstCodes.RightOffset 4)
    (InstCodesHelp.Label "Paste lines, commas, semicolons, or tabs")
    (InstCodesHelp.TopOffset 10) (InstCodesHelp.BottomOffset 5) (InstCodesHelp.LeftOffset 8)
    (InstPlanTitle.Label "3 LAYOUT")
    (InstPlanTitle.TopOffset 10) (InstPlanTitle.BottomOffset 6) (InstPlanTitle.LeftOffset 4)
    (InstColumnsLabel.Label "Columns")
    (InstColumnsLabel.TopOffset 6) (InstColumnsLabel.BottomOffset 6) (InstColumnsLabel.LeftOffset 6)
    (InstColumns.Columns 5)
    (InstColumns.TopOffset 5) (InstColumns.BottomOffset 5) (InstColumns.LeftOffset 4) (InstColumns.RightOffset 6)
    (InstGapLabel.Label "Gap")
    (InstGapLabel.TopOffset 6) (InstGapLabel.BottomOffset 6) (InstGapLabel.LeftOffset 6)
    (InstGap.Columns 8)
    (InstGap.TopOffset 5) (InstGap.BottomOffset 5) (InstGap.LeftOffset 4) (InstGap.RightOffset 6)
    (InstPlanButton.Label "Preview plan") (InstPlanButton.ButtonStyle 3)
    (InstPlanButton.HelpText "Refresh the requested-instance placement plan")
    (InstPlanButton.TopOffset 5) (InstPlanButton.BottomOffset 5) (InstPlanButton.LeftOffset 5) (InstPlanButton.RightOffset 6)
    (InstValidation.Label "")
    (InstValidation.TopOffset 6) (InstValidation.BottomOffset 6) (InstValidation.LeftOffset 8)
    (InstBuildReviewTitle.Label "4 BUILD")
    (InstBuildReviewTitle.TopOffset 10) (InstBuildReviewTitle.BottomOffset 6) (InstBuildReviewTitle.LeftOffset 4)
    (InstBuildButton.Label "Build assembly")
    (InstBuildButton.TopOffset 8) (InstBuildButton.BottomOffset 8) (InstBuildButton.LeftOffset 6) (InstBuildButton.RightOffset 6)
    (InstProgress.MinInteger 0) (InstProgress.MaxInteger 1) (InstProgress.Integer 0)
    (InstProgress.TopOffset 8) (InstProgress.BottomOffset 8) (InstProgress.LeftOffset 4) (InstProgress.RightOffset 4)
    (InstProgressText.Label "Ready")
    (InstProgressText.TopOffset 8) (InstProgressText.BottomOffset 8) (InstProgressText.LeftOffset 6)
    (InstResultsTitle.Label "RESULTS")
    (InstResultsTitle.TopOffset 10) (InstResultsTitle.BottomOffset 5) (InstResultsTitle.LeftOffset 4)
    (InstUnresolvedOnly.Label "Unresolved only")
    (InstUnresolvedOnly.TopOffset 8) (InstUnresolvedOnly.BottomOffset 5) (InstUnresolvedOnly.LeftOffset 6) (InstUnresolvedOnly.RightOffset 4)
    (InstResultsSpacer.Label "")
    (InstSummary.Label "No plan")
    (InstSummary.TopOffset 10) (InstSummary.BottomOffset 5) (InstSummary.LeftOffset 8)
    (InstTable.RowNames "empty")
    (InstTable.ColumnNames "Code" "Row" "Column" "Generic" "AddedModel" "Status")
    (InstTable.ColumnLabels "Code" "Row" "Col" "Generic" "Added model" "Status")
    (InstTable.ColumnWidths 24 7 7 24 25 12) (InstTable.VisibleRows 13)
    (InstTable.ShowGrid True) (InstTable.AttachLeft True) (InstTable.AttachRight True)
    (InstTable.AttachTop True) (InstTable.AttachBottom True)
    (InstTable.TopOffset 5) (InstTable.BottomOffset 6) (InstTable.LeftOffset 4) (InstTable.RightOffset 4)
    (InstDetails.Label "Missing codes keep their planned grid position.")
    (InstDetails.TopOffset 5) (InstDetails.BottomOffset 5) (InstDetails.LeftOffset 4)
    (InstExportButton.Label "Export CSV") (InstExportButton.ButtonStyle 3)
    (InstClearButton.Label "Clear") (InstClearButton.ButtonStyle 3)
    (InstExportButton.TopOffset 4) (InstExportButton.BottomOffset 4) (InstExportButton.LeftOffset 4) (InstExportButton.RightOffset 4)
    (InstClearButton.TopOffset 4) (InstClearButton.BottomOffset 4) (InstClearButton.LeftOffset 4) (InstClearButton.RightOffset 4)
    (InstSpacer.Label "")
    (FooterStatus.Label "Ready")
    (FooterStatus.TopOffset 8) (FooterStatus.BottomOffset 2) (FooterStatus.LeftOffset 4)
    (FooterCancelButton.Label "Cancel")
    (FooterCancelButton.TopOffset 6) (FooterCancelButton.BottomOffset 2) (FooterCancelButton.LeftOffset 6)
    (FullScreenButton.Label "Maximize / restore") (FullScreenButton.ButtonStyle 3)
    (FullScreenButton.HelpText "Maximize or restore this tool window")
    (FullScreenButton.TopOffset 4) (FullScreenButton.BottomOffset 4) (FullScreenButton.LeftOffset 4) (FullScreenButton.RightOffset 4)
    (ControlPanelButton.Label "Toolbox") (ControlPanelButton.ButtonStyle 3)
    (ControlPanelButton.HelpText "Return to the Control Panel")
    (ControlPanelButton.TopOffset 4) (ControlPanelButton.BottomOffset 4) (ControlPanelButton.LeftOffset 4) (ControlPanelButton.RightOffset 4)
    (CloseButton.Label "") (CloseButton.Bitmap "cl_cancel")
    (CloseButton.HelpText "Close") (CloseButton.ButtonStyle 3)
    (CloseButton.TopOffset 4) (CloseButton.BottomOffset 4) (CloseButton.LeftOffset 4) (CloseButton.RightOffset 4)
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        (Grid (Rows 0 0 0 0 0 0 0 0 0 1 0 0) (Cols 1)
          (Grid (Rows 0) (Cols 0 0 1 0 0) ControlPanelButton InstTitle InstDescription FullScreenButton CloseButton)
          (Grid (Rows 0) (Cols 0 1) InstTargetTitle InstActiveAsm)
          (Grid (Rows 0) (Cols 0 0 0 1 0) InstInputTitle InstSourceTitle InstFolderLabel InstFolder InstBrowseButton)
          (Grid (Rows 0) (Cols 0 0 1) InstRecursive InstLatest InstFound)
          (Grid (Rows 0) (Cols 0 1) InstCodesTitle InstCodesHelp)
          InstCodes
          (Grid (Rows 0) (Cols 0 0 0 0 0 0 1) InstPlanTitle InstColumnsLabel InstColumns InstGapLabel InstGap InstPlanButton InstValidation)
          (Grid (Rows 0) (Cols 0 0 1 0) InstBuildReviewTitle InstBuildButton InstProgress InstProgressText)
          (Grid (Rows 0) (Cols 0 0 1 0) InstResultsTitle InstSummary InstResultsSpacer InstUnresolvedOnly)
          InstTable
          InstDetails
          (Grid (Rows 0) (Cols 0 1 0) InstExportButton InstSpacer InstClearButton))
        (Grid (Rows 0) (Cols 1 0) FooterStatus FooterCancelButton)))))
