(Dialog aventics_weak
  (Components
    (Label WeakTitle) (Label WeakDescription) (Label WeakSourceTitle) (CheckButton WeakUseSelection)
    (Label WeakFolderLabel) (InputPanel WeakFolder) (PushButton WeakBrowseButton)
    (Label WeakOptionsTitle) (CheckButton WeakRecursive) (CheckButton WeakLatest) (Label WeakFound)
    (PushButton WeakRunButton) (ProgressBar WeakProgress) (Label WeakProgressText)
    (Label WeakResultsTitle) (Label WeakSearchLabel) (InputPanel WeakSearch) (CheckButton WeakIssuesOnly)
    (Table WeakTable) (Label WeakSummary) (Label WeakDetails)
    (PushButton WeakOpenButton) (PushButton WeakGotoButton) (PushButton WeakClearButton) (Label WeakSpacer)
    (Label FooterStatus) (PushButton FooterCancelButton) (PushButton FullScreenButton)
    (PushButton ControlPanelButton) (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox v0.5.2 - Weak Dimensions")
    (.Resizeable True) (.RememberSize True)
    (.TopOffset 8) (.BottomOffset 8) (.LeftOffset 8) (.RightOffset 8)
    (WeakTitle.Label "Weak Dimensions")
    (WeakTitle.TopOffset 5) (WeakTitle.BottomOffset 5) (WeakTitle.LeftOffset 4)
    (WeakDescription.Label "Read-only part check")
    (WeakDescription.TopOffset 5) (WeakDescription.BottomOffset 5) (WeakDescription.LeftOffset 8)
    (WeakSourceTitle.Label "SOURCE")
    (WeakSourceTitle.TopOffset 10) (WeakSourceTitle.BottomOffset 4) (WeakSourceTitle.LeftOffset 4)
    (WeakUseSelection.Label "Use selected parts") (WeakUseSelection.Set True)
    (WeakUseSelection.TopOffset 4) (WeakUseSelection.BottomOffset 4) (WeakUseSelection.LeftOffset 6) (WeakUseSelection.RightOffset 6)
    (WeakFolderLabel.Label "Folder")
    (WeakFolderLabel.TopOffset 4) (WeakFolderLabel.BottomOffset 4) (WeakFolderLabel.LeftOffset 6)
    (WeakFolder.Columns 52)
    (WeakFolder.TopOffset 4) (WeakFolder.BottomOffset 4) (WeakFolder.LeftOffset 4) (WeakFolder.RightOffset 4)
    (WeakBrowseButton.Label "Browse") (WeakBrowseButton.ButtonStyle 3) (WeakBrowseButton.HelpText "Choose a source folder")
    (WeakBrowseButton.TopOffset 4) (WeakBrowseButton.BottomOffset 4) (WeakBrowseButton.LeftOffset 4) (WeakBrowseButton.RightOffset 4)
    (WeakOptionsTitle.Label "Folder options")
    (WeakOptionsTitle.TopOffset 5) (WeakOptionsTitle.BottomOffset 5) (WeakOptionsTitle.LeftOffset 4)
    (WeakRecursive.Label "Include subfolders")
    (WeakRecursive.TopOffset 4) (WeakRecursive.BottomOffset 4) (WeakRecursive.LeftOffset 6) (WeakRecursive.RightOffset 6)
    (WeakLatest.Label "Latest only") (WeakLatest.Set True)
    (WeakLatest.TopOffset 4) (WeakLatest.BottomOffset 4) (WeakLatest.LeftOffset 6) (WeakLatest.RightOffset 6)
    (WeakFound.Label "Using selected parts")
    (WeakFound.TopOffset 4) (WeakFound.BottomOffset 4) (WeakFound.LeftOffset 8)
    (WeakRunButton.Label "Check")
    (WeakRunButton.TopOffset 8) (WeakRunButton.BottomOffset 8) (WeakRunButton.LeftOffset 4) (WeakRunButton.RightOffset 6)
    (WeakProgress.MinInteger 0) (WeakProgress.MaxInteger 1) (WeakProgress.Integer 0)
    (WeakProgress.TopOffset 8) (WeakProgress.BottomOffset 8) (WeakProgress.LeftOffset 4) (WeakProgress.RightOffset 4)
    (WeakProgressText.Label "Ready")
    (WeakProgressText.TopOffset 8) (WeakProgressText.BottomOffset 8) (WeakProgressText.LeftOffset 6)
    (WeakResultsTitle.Label "RESULTS")
    (WeakResultsTitle.TopOffset 10) (WeakResultsTitle.BottomOffset 5) (WeakResultsTitle.LeftOffset 4)
    (WeakSearchLabel.Label "Search")
    (WeakSearchLabel.TopOffset 8) (WeakSearchLabel.BottomOffset 5) (WeakSearchLabel.LeftOffset 6)
    (WeakSearch.Columns 26)
    (WeakSearch.TopOffset 6) (WeakSearch.BottomOffset 5) (WeakSearch.LeftOffset 4) (WeakSearch.RightOffset 4)
    (WeakIssuesOnly.Label "Issues only")
    (WeakIssuesOnly.TopOffset 7) (WeakIssuesOnly.BottomOffset 5) (WeakIssuesOnly.LeftOffset 6) (WeakIssuesOnly.RightOffset 6)
    (WeakTable.RowNames "empty")
    (WeakTable.ColumnNames "Part" "Status" "Feature" "Section" "Dimension")
    (WeakTable.ColumnLabels "Part" "Status" "Feature" "Section" "Weak dim")
    (WeakTable.ColumnWidths 25 11 28 9 11) (WeakTable.VisibleRows 15)
    (WeakTable.ShowGrid True) (WeakTable.AttachLeft True) (WeakTable.AttachRight True)
    (WeakTable.AttachTop True) (WeakTable.AttachBottom True)
    (WeakTable.TopOffset 5) (WeakTable.BottomOffset 6) (WeakTable.LeftOffset 4) (WeakTable.RightOffset 4)
    (WeakSummary.Label "No results")
    (WeakSummary.TopOffset 8) (WeakSummary.BottomOffset 5) (WeakSummary.LeftOffset 8)
    (WeakDetails.Label "Select a result for source and technical details.")
    (WeakDetails.TopOffset 5) (WeakDetails.BottomOffset 5) (WeakDetails.LeftOffset 4)
    (WeakOpenButton.Label "Open") (WeakOpenButton.ButtonStyle 3)
    (WeakGotoButton.Label "Go to feature") (WeakGotoButton.ButtonStyle 3)
    (WeakClearButton.Label "Clear") (WeakClearButton.ButtonStyle 3)
    (WeakOpenButton.TopOffset 4) (WeakOpenButton.BottomOffset 4) (WeakOpenButton.LeftOffset 4) (WeakOpenButton.RightOffset 4)
    (WeakGotoButton.TopOffset 4) (WeakGotoButton.BottomOffset 4) (WeakGotoButton.LeftOffset 4) (WeakGotoButton.RightOffset 4)
    (WeakClearButton.TopOffset 4) (WeakClearButton.BottomOffset 4) (WeakClearButton.LeftOffset 4) (WeakClearButton.RightOffset 4)
    (WeakSpacer.Label "")
    (FooterStatus.Label "Ready")
    (FooterStatus.TopOffset 8) (FooterStatus.BottomOffset 2) (FooterStatus.LeftOffset 4)
    (FooterCancelButton.Label "Cancel")
    (FooterCancelButton.TopOffset 6) (FooterCancelButton.BottomOffset 2) (FooterCancelButton.LeftOffset 6)
    (FullScreenButton.Label "Maximize / restore") (FullScreenButton.ButtonStyle 3)
    (FullScreenButton.HelpText "Maximize or restore this tool window")
    (FullScreenButton.TopOffset 4) (FullScreenButton.BottomOffset 4) (FullScreenButton.LeftOffset 4) (FullScreenButton.RightOffset 4)
    (ControlPanelButton.Label "Toolbox") (ControlPanelButton.ButtonStyle 3)
    (ControlPanelButton.HelpText "Return to the Control Panel")
    (ControlPanelButton.TopOffset 4) (ControlPanelButton.BottomOffset 4) (ControlPanelButton.LeftOffset 4) (ControlPanelButton.RightOffset 4)
    (CloseButton.Label "") (CloseButton.Bitmap "cl_cancel")
    (CloseButton.HelpText "Close") (CloseButton.ButtonStyle 3)
    (CloseButton.TopOffset 4) (CloseButton.BottomOffset 4) (CloseButton.LeftOffset 4) (CloseButton.RightOffset 4)
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        (Grid (Rows 0 0 0 0 0 1 0 0) (Cols 1)
          (Grid (Rows 0) (Cols 0 0 1 0 0) ControlPanelButton WeakTitle WeakDescription FullScreenButton CloseButton)
          (Grid (Rows 0) (Cols 0 0 0 1 0) WeakSourceTitle WeakUseSelection WeakFolderLabel WeakFolder WeakBrowseButton)
          (Grid (Rows 0) (Cols 0 0 0 1) WeakOptionsTitle WeakRecursive WeakLatest WeakFound)
          (Grid (Rows 0) (Cols 0 1 0) WeakRunButton WeakProgress WeakProgressText)
          (Grid (Rows 0) (Cols 0 1 0 0 0) WeakResultsTitle WeakSummary WeakIssuesOnly WeakSearchLabel WeakSearch)
          WeakTable
          WeakDetails
          (Grid (Rows 0) (Cols 0 0 1 0) WeakOpenButton WeakGotoButton WeakSpacer WeakClearButton))
        (Grid (Rows 0) (Cols 1 0) FooterStatus FooterCancelButton)))))
