(Dialog aventics_inspection
  (Components
    (Label InspTitle) (Label InspDescription) (Label InspTargetTitle) (Label InspActiveAsm)
    (Label InspSourceTitle) (Label InspFolderLabel) (InputPanel InspFolder) (PushButton InspBrowseButton)
    (Label InspDiscoveryLabel) (CheckButton InspRecursive) (CheckButton InspLatest)
    (Label InspTypesLabel) (CheckButton InspParts) (CheckButton InspAssemblies) (CheckButton InspStep)
    (Label InspFamilyGroupLabel) (CheckButton InspFamily) (CheckButton InspGeneric) (Label InspFound)
    (Label InspPlacementTitle) (Label InspArrangementLabel) (CheckButton InspArrange)
    (Label InspDirectionLabel) (CheckButton InspRowsAlongX) (Label InspPlaneLabel) (CheckButton InspUseZAxis)
    (Label InspGridLabel) (Label InspColumnsLabel) (InputPanel InspColumns) (Label InspGapLabel) (InputPanel InspGap)
    (Label InspValidation) (PushButton InspBuildButton)
    (ProgressBar InspProgress) (Label InspProgressText) (Label InspResultsTitle)
    (Table InspTable) (Label InspSummary) (Label InspDetails)
    (PushButton InspClearButton) (Label InspSpacer)
    (Label FooterStatus) (PushButton FooterCancelButton) (PushButton FullScreenButton)
    (PushButton ControlPanelButton) (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox v0.5.1 - Inspection")
    (.Resizeable True) (.RememberSize True)
    (InspTitle.Label "Inspection builder")
    (InspDescription.Label "Assembly placement")
    (InspTargetTitle.Label "Target") (InspActiveAsm.Label "No active assembly")
    (InspSourceTitle.Label "Source") (InspFolderLabel.Label "Folder")
    (InspFolder.Columns 52) (InspBrowseButton.Label "Browse")
    (InspDiscoveryLabel.Label "Scan")
    (InspRecursive.Label "Subfolders")
    (InspLatest.Label "Latest only") (InspLatest.Set True)
    (InspTypesLabel.Label "Models")
    (InspParts.Label "Parts") (InspParts.Set True)
    (InspAssemblies.Label "Assemblies") (InspAssemblies.Set True)
    (InspStep.Label "STEP") (InspStep.Set True)
    (InspFamilyGroupLabel.Label "Family")
    (InspFamily.Label "Instances") (InspFamily.Set True)
    (InspGeneric.Label "Generic")
    (InspFound.Label "Choose source folder")
    (InspPlacementTitle.Label "Placement")
    (InspArrangementLabel.Label "")
    (InspArrange.Label "Auto arrange") (InspArrange.Set True)
    (InspDirectionLabel.Label "")
    (InspRowsAlongX.Label "Rows along X")
    (InspPlaneLabel.Label "")
    (InspUseZAxis.Label "X-Z plane")
    (InspGridLabel.Label "Grid")
    (InspColumnsLabel.Label "Columns") (InspColumns.Columns 5)
    (InspGapLabel.Label "Gap") (InspGap.Columns 8)
    (InspValidation.Label "") (InspBuildButton.Label "Build")
    (InspProgress.MinInteger 0) (InspProgress.MaxInteger 1) (InspProgress.Integer 0)
    (InspProgressText.Label "Ready") (InspResultsTitle.Label "Results")
    (InspTable.RowNames "empty")
    (InspTable.ColumnNames "Source" "Kind" "AddedModel" "Status" "FeatureId")
    (InspTable.ColumnLabels "Source" "Kind" "Added model" "Status" "Feature")
    (InspTable.ColumnWidths 29 14 29 12 9) (InspTable.VisibleRows 12)
    (InspTable.ShowGrid True) (InspTable.AttachLeft True) (InspTable.AttachRight True)
    (InspTable.AttachTop True) (InspTable.AttachBottom True)
    (InspSummary.Label "No results")
    (InspDetails.Label "Select a row for details.")
    (InspClearButton.Label "Clear") (InspSpacer.Label "")
    (FooterStatus.Label "Ready") (FooterCancelButton.Label "Cancel")
    (FullScreenButton.Label "Full screen") (ControlPanelButton.Label "Home") (CloseButton.Label "Close")
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        (Grid (Rows 0 0 0 0 0 0 0 0 0 1 0 0 0) (Cols 1)
          (Grid (Rows 0) (Cols 0 1) InspTitle InspDescription)
          (Grid (Rows 0) (Cols 0 1) InspTargetTitle InspActiveAsm)
          (Grid (Rows 0) (Cols 0 0 1 0) InspSourceTitle InspFolderLabel InspFolder InspBrowseButton)
          (Grid (Rows 0) (Cols 0 0 0 0 0 0 0 1) InspDiscoveryLabel InspRecursive InspLatest InspTypesLabel InspParts InspAssemblies InspStep InspFound)
          (Grid (Rows 0) (Cols 0 0 1) InspFamilyGroupLabel InspFamily InspGeneric)
          (Grid (Rows 0) (Cols 0 0 0 0 0 0 1) InspPlacementTitle InspArrangementLabel InspArrange InspDirectionLabel InspRowsAlongX InspPlaneLabel InspUseZAxis)
          (Grid (Rows 0) (Cols 0 0 0 0 0 1) InspGridLabel InspColumnsLabel InspColumns InspGapLabel InspGap InspValidation)
          (Grid (Rows 0) (Cols 0 1 0) InspBuildButton InspProgress InspProgressText)
          InspResultsTitle InspTable InspSummary InspDetails
          (Grid (Rows 0) (Cols 0 1) InspClearButton InspSpacer))
        (Grid (Rows 0) (Cols 1 0 0 0 0)
          FooterStatus FooterCancelButton FullScreenButton ControlPanelButton CloseButton)))))
