(Dialog aventics_toolbox
  (Components
    (Tab ToolTabs OverviewLayout WeakLayout AccuracyLayout InspectionLayout)
    (Label FooterStatus)
    (PushButton FooterCancelButton)
    (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox - v0.3.0")
    (.Resizeable True) (.RememberSize True)
    (ToolTabs.Decorated True)
    (ToolTabs.AttachLeft True) (ToolTabs.AttachRight True)
    (ToolTabs.AttachTop True) (ToolTabs.AttachBottom True)
    (ToolTabs.LeftOffset 8) (ToolTabs.RightOffset 8)
    (ToolTabs.TopOffset 8) (ToolTabs.BottomOffset 8)
    (FooterStatus.Label "Ready")
    (FooterCancelButton.Label "Cancel operation")
    (CloseButton.Label "Close")
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        ToolTabs
        (Grid (Rows 0) (Cols 1 0 0) FooterStatus FooterCancelButton CloseButton)))))

(Layout OverviewLayout
  (Components
    (Label OverviewTitle) (Label OverviewIntro)
    (Label OverviewQcTitle) (Label OverviewQcDesc)
    (PushButton OverviewRunAllButton) (Label OverviewRunAllStatus)
    (PushButton OverviewWeakButton) (PushButton OverviewAccButton)
    (Label OverviewInspectionTitle) (Label OverviewInspDesc)
    (PushButton OverviewInspButton) (Label OverviewSafety) (Label OverviewSpacer))
  (Resources
    (.Label "Overview")
    (OverviewTitle.Label "Aventics Toolbox")
    (OverviewIntro.Label "Quality-control and inspection utilities for Creo Parametric.")
    (OverviewQcTitle.Label "Quality control")
    (OverviewQcDesc.Label "Check selected parts and assemblies. Weak Dimensions applies to parts; Accuracy applies to both.")
    (OverviewRunAllButton.Label "Run all QC on Creo selection")
    (OverviewRunAllStatus.Label "Ready. Results appear in the Weak Dimensions and Accuracy tabs.")
    (OverviewWeakButton.Label "Review weak dimensions")
    (OverviewAccButton.Label "Review accuracy")
    (OverviewInspectionTitle.Label "Inspection assembly")
    (OverviewInspDesc.Label "Add Creo and STEP sources to the active assembly for manual inspection.")
    (OverviewInspButton.Label "Open inspection builder")
    (OverviewSafety.Label "QC is read-only. Inspection adds unconstrained components and never saves automatically.")
    (OverviewSpacer.Label "")
    (.Decorated False)
    (.TopOffset 12) (.BottomOffset 12) (.LeftOffset 12) (.RightOffset 12)
    (.Layout
      (Grid (Rows 0 0 0 0 0 0 0 0 0 0 1) (Cols 1)
        OverviewTitle OverviewIntro OverviewQcTitle OverviewQcDesc
        OverviewRunAllButton OverviewRunAllStatus
        (Grid (Rows 0) (Cols 0 0 1) OverviewWeakButton OverviewAccButton OverviewSpacer)
        OverviewInspectionTitle OverviewInspDesc OverviewInspButton OverviewSafety))))

(Layout WeakLayout
  (Components
    (Label WeakTitle) (Label WeakDescription) (CheckButton WeakUseSelection)
    (Label WeakFolderLabel) (InputPanel WeakFolder) (PushButton WeakBrowseButton)
    (CheckButton WeakRecursive) (CheckButton WeakLatest) (Label WeakFound)
    (PushButton WeakRunButton) (ProgressBar WeakProgress) (Label WeakProgressText)
    (Label WeakResultsTitle) (Label WeakSearchLabel) (InputPanel WeakSearch) (CheckButton WeakIssuesOnly)
    (Table WeakTable) (Label WeakSummary) (Label WeakDetails)
    (PushButton WeakOpenButton) (PushButton WeakGotoButton) (PushButton WeakClearButton)
    (Label WeakSpacer))
  (Resources
    (.Label "Weak Dimensions")
    (WeakTitle.Label "Weak dimensions")
    (WeakDescription.Label "Find weak section dimensions in selected parts or all eligible parts in a folder.")
    (WeakUseSelection.Label "Use Creo selection") (WeakUseSelection.Set True)
    (WeakFolderLabel.Label "Folder") (WeakFolder.Columns 64)
    (WeakBrowseButton.Label "Browse...")
    (WeakRecursive.Label "Include subfolders")
    (WeakLatest.Label "Latest Creo file version only") (WeakLatest.Set True)
    (WeakFound.Label "Selection mode: choose parts after starting the check.")
    (WeakRunButton.Label "Check dimensions")
    (WeakProgress.MinInteger 0) (WeakProgress.MaxInteger 1) (WeakProgress.Integer 0)
    (WeakProgressText.Label "Ready")
    (WeakResultsTitle.Label "Results") (WeakSearchLabel.Label "Search") (WeakSearch.Columns 28)
    (WeakIssuesOnly.Label "Issues only")
    (WeakTable.RowNames "empty")
    (WeakTable.ColumnNames "Part" "Status" "Feature" "Section" "Dimension" "Details")
    (WeakTable.ColumnLabels "Part" "Status" "Feature" "Section" "Weak dim" "Details")
    (WeakTable.ColumnWidths 22 10 22 8 10 44) (WeakTable.VisibleRows 12)
    (WeakTable.ShowGrid True) (WeakTable.AttachLeft True) (WeakTable.AttachRight True)
    (WeakTable.AttachTop True) (WeakTable.AttachBottom True)
    (WeakSummary.Label "No results")
    (WeakDetails.Label "Select a result to see its source and technical details.")
    (WeakOpenButton.Label "Open part") (WeakGotoButton.Label "Go to feature")
    (WeakClearButton.Label "Clear results") (WeakSpacer.Label "")
    (.Decorated False)
    (.TopOffset 8) (.BottomOffset 8) (.LeftOffset 8) (.RightOffset 8)
    (.Layout
      (Grid (Rows 0 0 0 0 0 0 0 0 1 0 0 0) (Cols 1)
        WeakTitle WeakDescription WeakUseSelection
        (Grid (Rows 0) (Cols 0 1 0) WeakFolderLabel WeakFolder WeakBrowseButton)
        (Grid (Rows 0) (Cols 0 0 1) WeakRecursive WeakLatest WeakFound)
        (Grid (Rows 0) (Cols 0 1 0) WeakRunButton WeakProgress WeakProgressText)
        WeakResultsTitle
        (Grid (Rows 0) (Cols 0 0 1) WeakIssuesOnly WeakSearchLabel WeakSearch)
        WeakTable WeakSummary WeakDetails
        (Grid (Rows 0) (Cols 0 0 0 1) WeakOpenButton WeakGotoButton WeakClearButton WeakSpacer)))))

(Layout AccuracyLayout
  (Components
    (Label AccTitle) (Label AccRule) (CheckButton AccUseSelection)
    (Label AccFolderLabel) (InputPanel AccFolder) (PushButton AccBrowseButton)
    (CheckButton AccRecursive) (CheckButton AccLatest)
    (CheckButton AccParts) (CheckButton AccAssemblies) (Label AccFound)
    (PushButton AccRunButton) (ProgressBar AccProgress) (Label AccProgressText)
    (Label AccResultsTitle) (Label AccSearchLabel) (InputPanel AccSearch) (CheckButton AccIssuesOnly)
    (Table AccTable) (Label AccSummary) (Label AccDetails)
    (PushButton AccOpenButton) (PushButton AccClearButton) (Label AccSpacer))
  (Resources
    (.Label "Accuracy")
    (AccTitle.Label "Model accuracy")
    (AccRule.Label "Required: ABSOLUTE accuracy = 0.001")
    (AccUseSelection.Label "Use Creo selection") (AccUseSelection.Set True)
    (AccFolderLabel.Label "Folder") (AccFolder.Columns 64)
    (AccBrowseButton.Label "Browse...")
    (AccRecursive.Label "Include subfolders")
    (AccLatest.Label "Latest Creo file version only") (AccLatest.Set True)
    (AccParts.Label "Parts") (AccParts.Set True)
    (AccAssemblies.Label "Assemblies") (AccAssemblies.Set True)
    (AccFound.Label "Selection mode: choose models after starting the check.")
    (AccRunButton.Label "Check accuracy")
    (AccProgress.MinInteger 0) (AccProgress.MaxInteger 1) (AccProgress.Integer 0)
    (AccProgressText.Label "Ready")
    (AccResultsTitle.Label "Results") (AccSearchLabel.Label "Search") (AccSearch.Columns 28)
    (AccIssuesOnly.Label "Issues only")
    (AccTable.RowNames "empty")
    (AccTable.ColumnNames "Model" "Kind" "AccuracyType" "Accuracy" "Status" "Details")
    (AccTable.ColumnLabels "Model" "Kind" "Accuracy type" "Accuracy" "Status" "Details")
    (AccTable.ColumnWidths 24 11 14 12 10 44) (AccTable.VisibleRows 12)
    (AccTable.ShowGrid True) (AccTable.AttachLeft True) (AccTable.AttachRight True)
    (AccTable.AttachTop True) (AccTable.AttachBottom True)
    (AccSummary.Label "No results")
    (AccDetails.Label "Select a result to see its source and technical details.")
    (AccOpenButton.Label "Open model") (AccClearButton.Label "Clear results")
    (AccSpacer.Label "")
    (.Decorated False)
    (.TopOffset 8) (.BottomOffset 8) (.LeftOffset 8) (.RightOffset 8)
    (.Layout
      (Grid (Rows 0 0 0 0 0 0 0 0 1 0 0 0) (Cols 1)
        AccTitle AccRule AccUseSelection
        (Grid (Rows 0) (Cols 0 1 0) AccFolderLabel AccFolder AccBrowseButton)
        (Grid (Rows 0) (Cols 0 0 0 0 1) AccRecursive AccLatest AccParts AccAssemblies AccFound)
        (Grid (Rows 0) (Cols 0 1 0) AccRunButton AccProgress AccProgressText)
        AccResultsTitle
        (Grid (Rows 0) (Cols 0 0 1) AccIssuesOnly AccSearchLabel AccSearch)
        AccTable AccSummary AccDetails
        (Grid (Rows 0) (Cols 0 0 1) AccOpenButton AccClearButton AccSpacer)))))

(Layout InspectionLayout
  (Components
    (Label InspTitle) (Label InspDescription) (Label InspTargetTitle) (Label InspActiveAsm)
    (Label InspSourceTitle) (Label InspFolderLabel) (InputPanel InspFolder) (PushButton InspBrowseButton)
    (CheckButton InspRecursive) (CheckButton InspLatest) (CheckButton InspParts)
    (CheckButton InspAssemblies) (CheckButton InspFamily) (CheckButton InspGeneric)
    (CheckButton InspStep) (Label InspFound)
    (Label InspPlacementTitle) (CheckButton InspArrange) (CheckButton InspRowsAlongX)
    (Label InspColumnsLabel) (InputPanel InspColumns) (Label InspGapLabel) (InputPanel InspGap)
    (Label InspValidation) (PushButton InspBuildButton)
    (ProgressBar InspProgress) (Label InspProgressText) (Label InspResultsTitle)
    (Table InspTable) (Label InspSummary) (Label InspDetails)
    (PushButton InspClearButton) (Label InspSpacer))
  (Resources
    (.Label "Inspection")
    (InspTitle.Label "Inspection assembly builder")
    (InspDescription.Label "Add discovered models without constraints. The active assembly is never saved automatically.")
    (InspTargetTitle.Label "Target assembly") (InspActiveAsm.Label "No active assembly")
    (InspSourceTitle.Label "Source files") (InspFolderLabel.Label "Folder")
    (InspFolder.Columns 64) (InspBrowseButton.Label "Browse...")
    (InspRecursive.Label "Include subfolders")
    (InspLatest.Label "Latest Creo file version only") (InspLatest.Set True)
    (InspParts.Label "Creo parts") (InspParts.Set True)
    (InspAssemblies.Label "Creo assemblies") (InspAssemblies.Set True)
    (InspFamily.Label "Family-table instances") (InspFamily.Set True)
    (InspGeneric.Label "Also include family generic")
    (InspStep.Label "STEP (.stp/.step)") (InspStep.Set True)
    (InspFound.Label "Choose a folder to discover eligible source files.")
    (InspPlacementTitle.Label "Placement")
    (InspArrange.Label "Auto arrange") (InspArrange.Set True)
    (InspRowsAlongX.Label "Arrange rows along X axis (horizontal)")
    (InspColumnsLabel.Label "Columns") (InspColumns.Columns 5)
    (InspGapLabel.Label "Gap (assembly units)") (InspGap.Columns 8)
    (InspValidation.Label "") (InspBuildButton.Label "Add to assembly")
    (InspProgress.MinInteger 0) (InspProgress.MaxInteger 1) (InspProgress.Integer 0)
    (InspProgressText.Label "Ready") (InspResultsTitle.Label "Results")
    (InspTable.RowNames "empty")
    (InspTable.ColumnNames "Source" "Kind" "AddedModel" "Status" "FeatureId" "Details")
    (InspTable.ColumnLabels "Source" "Kind" "Added model" "Status" "Feature ID" "Details")
    (InspTable.ColumnWidths 22 14 22 10 10 44) (InspTable.VisibleRows 9)
    (InspTable.ShowGrid True) (InspTable.AttachLeft True) (InspTable.AttachRight True)
    (InspTable.AttachTop True) (InspTable.AttachBottom True)
    (InspSummary.Label "No results")
    (InspDetails.Label "Select a result to see its source and technical details.")
    (InspClearButton.Label "Clear results") (InspSpacer.Label "")
    (.Decorated False)
    (.TopOffset 8) (.BottomOffset 8) (.LeftOffset 8) (.RightOffset 8)
    (.Layout
      (Grid (Rows 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0) (Cols 1)
        InspTitle InspDescription InspTargetTitle InspActiveAsm InspSourceTitle
        (Grid (Rows 0) (Cols 0 1 0) InspFolderLabel InspFolder InspBrowseButton)
        (Grid (Rows 0) (Cols 0 0 0 0 1) InspRecursive InspLatest InspParts InspAssemblies InspFound)
        (Grid (Rows 0) (Cols 0 0 1) InspFamily InspGeneric InspStep)
        InspPlacementTitle
        (Grid (Rows 0) (Cols 0 0 0 0 0 0 1) InspArrange InspRowsAlongX InspColumnsLabel InspColumns InspGapLabel InspGap InspValidation)
        (Grid (Rows 0) (Cols 0 1 0) InspBuildButton InspProgress InspProgressText)
        InspResultsTitle InspTable InspSummary InspDetails
        (Grid (Rows 0) (Cols 0 1) InspClearButton InspSpacer)))))
