(Dialog aventics_weak
  (Components
    (Label WeakTitle) (Label WeakDescription) (Label WeakSourceTitle) (CheckButton WeakUseSelection)
    (Label WeakFolderLabel) (InputPanel WeakFolder) (PushButton WeakBrowseButton)
    (Label WeakOptionsTitle) (CheckButton WeakRecursive) (CheckButton WeakLatest) (Label WeakFound)
    (PushButton WeakRunButton) (ProgressBar WeakProgress) (Label WeakProgressText)
    (Label WeakResultsTitle) (Label WeakSearchLabel) (InputPanel WeakSearch) (CheckButton WeakIssuesOnly)
    (Table WeakTable) (Label WeakSummary) (Label WeakDetails)
    (PushButton WeakOpenButton) (PushButton WeakGotoButton) (PushButton WeakClearButton) (Label WeakSpacer)
    (Label FooterStatus) (PushButton FooterCancelButton) (PushButton FullScreenButton)
    (PushButton ControlPanelButton) (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox v0.5.1 - Weak Dimensions")
    (.Resizeable True) (.RememberSize True)
    (WeakTitle.Label "Weak dimensions")
    (WeakDescription.Label "Read-only part check")
    (WeakSourceTitle.Label "Source")
    (WeakUseSelection.Label "Creo selection") (WeakUseSelection.Set True)
    (WeakFolderLabel.Label "Folder") (WeakFolder.Columns 52)
    (WeakBrowseButton.Label "Browse")
    (WeakOptionsTitle.Label "Options")
    (WeakRecursive.Label "Subfolders")
    (WeakLatest.Label "Latest only") (WeakLatest.Set True)
    (WeakFound.Label "Selection source")
    (WeakRunButton.Label "Check")
    (WeakProgress.MinInteger 0) (WeakProgress.MaxInteger 1) (WeakProgress.Integer 0)
    (WeakProgressText.Label "Ready")
    (WeakResultsTitle.Label "Results") (WeakSearchLabel.Label "Search") (WeakSearch.Columns 26)
    (WeakIssuesOnly.Label "Issues only")
    (WeakTable.RowNames "empty")
    (WeakTable.ColumnNames "Part" "Status" "Feature" "Section" "Dimension")
    (WeakTable.ColumnLabels "Part" "Status" "Feature" "Section" "Weak dim")
    (WeakTable.ColumnWidths 25 11 28 9 11) (WeakTable.VisibleRows 14)
    (WeakTable.ShowGrid True) (WeakTable.AttachLeft True) (WeakTable.AttachRight True)
    (WeakTable.AttachTop True) (WeakTable.AttachBottom True)
    (WeakSummary.Label "No results")
    (WeakDetails.Label "Select a row for details.")
    (WeakOpenButton.Label "Open") (WeakGotoButton.Label "Feature")
    (WeakClearButton.Label "Clear") (WeakSpacer.Label "")
    (FooterStatus.Label "Ready") (FooterCancelButton.Label "Cancel")
    (FullScreenButton.Label "Full screen") (ControlPanelButton.Label "Home") (CloseButton.Label "Close")
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        (Grid (Rows 0 0 0 0 0 1 0 0 0) (Cols 1)
          (Grid (Rows 0) (Cols 0 1) WeakTitle WeakDescription)
          (Grid (Rows 0) (Cols 0 0 0 1 0) WeakSourceTitle WeakUseSelection WeakFolderLabel WeakFolder WeakBrowseButton)
          (Grid (Rows 0) (Cols 0 0 0 1) WeakOptionsTitle WeakRecursive WeakLatest WeakFound)
          (Grid (Rows 0) (Cols 0 1 0) WeakRunButton WeakProgress WeakProgressText)
          (Grid (Rows 0) (Cols 0 0 0 1) WeakResultsTitle WeakIssuesOnly WeakSearchLabel WeakSearch)
          WeakTable WeakSummary WeakDetails
          (Grid (Rows 0) (Cols 0 0 0 1) WeakOpenButton WeakGotoButton WeakClearButton WeakSpacer))
        (Grid (Rows 0) (Cols 1 0 0 0 0)
          FooterStatus FooterCancelButton FullScreenButton ControlPanelButton CloseButton)))))
