(Dialog aventics_toolbox
  (Components
    (Label OverviewTitle) (Label OverviewIntro)
    (Label OverviewQcTitle) (Label OverviewQcDesc)
    (PushButton OverviewRunAllButton) (Label OverviewRunAllStatus)
    (PushButton OverviewWeakButton) (PushButton OverviewAccButton) (Label OverviewQcSpacer)
    (Label OverviewAssemblyTitle) (Label OverviewAssemblyDesc)
    (PushButton OverviewInspButton) (PushButton OverviewInstButton) (Label OverviewAssemblySpacer)
    (Label OverviewSafety) (Label OverviewSpacer)
    (Label FooterStatus) (PushButton FooterCancelButton) (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox v0.5.1 - Control Panel")
    (.Resizeable True) (.RememberSize True)
    (OverviewTitle.Label "Aventics Toolbox")
    (OverviewIntro.Label "Creo engineering tools")
    (OverviewQcTitle.Label "Quality")
    (OverviewQcDesc.Label "Read-only")
    (OverviewRunAllButton.Label "Run all checks")
    (OverviewRunAllStatus.Label "Ready")
    (OverviewWeakButton.Label "Weak dimensions")
    (OverviewAccButton.Label "Accuracy")
    (OverviewQcSpacer.Label "")
    (OverviewAssemblyTitle.Label "Assembly")
    (OverviewAssemblyDesc.Label "Placement")
    (OverviewInspButton.Label "Inspection builder")
    (OverviewInstButton.Label "Instance builder")
    (OverviewAssemblySpacer.Label "")
    (OverviewSafety.Label "No auto-save")
    (OverviewSpacer.Label "")
    (FooterStatus.Label "Ready")
    (FooterCancelButton.Label "Cancel")
    (CloseButton.Label "Close")
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        (Grid (Rows 0 0 0 0 0 1) (Cols 1)
          (Grid (Rows 0) (Cols 0 1) OverviewTitle OverviewIntro)
          (Grid (Rows 0) (Cols 0 0 1 0) OverviewQcTitle OverviewQcDesc OverviewQcSpacer OverviewRunAllButton)
          (Grid (Rows 0) (Cols 0 0 1) OverviewWeakButton OverviewAccButton OverviewRunAllStatus)
          (Grid (Rows 0) (Cols 0 0 1) OverviewAssemblyTitle OverviewAssemblyDesc OverviewAssemblySpacer)
          (Grid (Rows 0) (Cols 0 0 1) OverviewInspButton OverviewInstButton OverviewSafety)
          OverviewSpacer)
        (Grid (Rows 0) (Cols 1 0 0) FooterStatus FooterCancelButton CloseButton)))))
