(Dialog aventics_instance_builder
  (Components
    (Label InstTitle) (Label InstDescription) (Label InstTargetTitle) (Label InstActiveAsm)
    (Label InstInputTitle) (Label InstSourceTitle) (Label InstFolderLabel) (InputPanel InstFolder) (PushButton InstBrowseButton)
    (CheckButton InstRecursive) (CheckButton InstLatest) (Label InstFound)
    (Label InstCodesTitle) (TextArea InstCodes) (Label InstCodesHelp)
    (Label InstPlanTitle) (Label InstColumnsLabel) (InputPanel InstColumns)
    (Label InstGapLabel) (InputPanel InstGap) (PushButton InstPlanButton) (Label InstValidation)
    (Label InstBuildReviewTitle) (PushButton InstBuildButton) (ProgressBar InstProgress) (Label InstProgressText)
    (Label InstResultsTitle) (CheckButton InstUnresolvedOnly) (Label InstResultsSpacer)
    (Table InstTable) (Label InstSummary) (Label InstDetails)
    (PushButton InstExportButton) (PushButton InstClearButton) (Label InstSpacer)
    (Label FooterStatus) (PushButton FooterCancelButton) (PushButton FullScreenButton)
    (PushButton ControlPanelButton) (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox v0.5.2 - Instance Builder")
    (.Resizeable True) (.RememberSize True)
    (InstTitle.Label "Instance Builder")
    (InstDescription.Label "Exact requested-instance placement")
    (InstTargetTitle.Label "TARGET") (InstActiveAsm.Label "No active assembly")
    (InstInputTitle.Label "1 SOURCE")
    (InstSourceTitle.Label "Search") (InstFolderLabel.Label "Folder")
    (InstFolder.Columns 52) (InstBrowseButton.Label "Browse")
    (InstRecursive.Label "Include subfolders")
    (InstLatest.Label "Latest only") (InstLatest.Set True)
    (InstFound.Label "Choose a source folder")
    (InstCodesTitle.Label "2 REQUESTED CODES")
    (InstCodes.Rows 10) (InstCodes.Columns 64) (InstCodes.MinRows 6) (InstCodes.MaxLen 32767)
    (InstCodes.AttachLeft True) (InstCodes.AttachRight True)
    (InstCodesHelp.Label "Paste lines, commas, semicolons, or tabs")
    (InstPlanTitle.Label "3 LAYOUT")
    (InstColumnsLabel.Label "Columns") (InstColumns.Columns 5)
    (InstGapLabel.Label "Gap") (InstGap.Columns 8)
    (InstPlanButton.Label "Preview plan")
    (InstValidation.Label "")
    (InstBuildReviewTitle.Label "4 BUILD")
    (InstBuildButton.Label "Build assembly")
    (InstProgress.MinInteger 0) (InstProgress.MaxInteger 1) (InstProgress.Integer 0)
    (InstProgressText.Label "Ready")
    (InstResultsTitle.Label "RESULTS")
    (InstUnresolvedOnly.Label "Unresolved only")
    (InstResultsSpacer.Label "")
    (InstTable.RowNames "empty")
    (InstTable.ColumnNames "Code" "Row" "Column" "Generic" "AddedModel" "Status")
    (InstTable.ColumnLabels "Code" "Row" "Col" "Generic" "Added model" "Status")
    (InstTable.ColumnWidths 24 7 7 24 25 12) (InstTable.VisibleRows 13)
    (InstTable.ShowGrid True) (InstTable.AttachLeft True) (InstTable.AttachRight True)
    (InstTable.AttachTop True) (InstTable.AttachBottom True)
    (InstSummary.Label "No plan")
    (InstDetails.Label "Missing codes keep their planned grid position.")
    (InstExportButton.Label "Export CSV")
    (InstClearButton.Label "Clear") (InstSpacer.Label "")
    (FooterStatus.Label "Ready") (FooterCancelButton.Label "Cancel")
    (FullScreenButton.Label "Maximize / restore") (ControlPanelButton.Label "Toolbox") (CloseButton.Label "Close")
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        (Grid (Rows 0 0 0 0 0 0 0 0 0 1 0 0) (Cols 1)
          (Grid (Rows 0) (Cols 0 0 1 0 0) ControlPanelButton InstTitle InstDescription FullScreenButton CloseButton)
          (Grid (Rows 0) (Cols 0 1) InstTargetTitle InstActiveAsm)
          (Grid (Rows 0) (Cols 0 0 0 1 0) InstInputTitle InstSourceTitle InstFolderLabel InstFolder InstBrowseButton)
          (Grid (Rows 0) (Cols 0 0 1) InstRecursive InstLatest InstFound)
          (Grid (Rows 0) (Cols 0 1) InstCodesTitle InstCodesHelp)
          InstCodes
          (Grid (Rows 0) (Cols 0 0 0 0 0 0 1) InstPlanTitle InstColumnsLabel InstColumns InstGapLabel InstGap InstPlanButton InstValidation)
          (Grid (Rows 0) (Cols 0 0 1 0) InstBuildReviewTitle InstBuildButton InstProgress InstProgressText)
          (Grid (Rows 0) (Cols 0 0 1 0) InstResultsTitle InstSummary InstResultsSpacer InstUnresolvedOnly)
          InstTable
          InstDetails
          (Grid (Rows 0) (Cols 0 1 0) InstExportButton InstSpacer InstClearButton))
        (Grid (Rows 0) (Cols 1 0) FooterStatus FooterCancelButton)))))
