(Dialog aventics_inspection
  (Components
    (Label InspTitle) (Label InspDescription) (Label InspTargetTitle) (Label InspActiveAsm)
    (Label InspSourceTitle) (Label InspFolderLabel) (InputPanel InspFolder) (PushButton InspBrowseButton)
    (Label InspDiscoveryLabel) (CheckButton InspRecursive) (CheckButton InspLatest)
    (Label InspTypesLabel) (CheckButton InspParts) (CheckButton InspAssemblies) (CheckButton InspStep)
    (Label InspFamilyGroupLabel) (CheckButton InspFamily) (CheckButton InspGeneric) (Label InspFound)
    (Label InspPlacementTitle) (Label InspArrangementLabel) (CheckButton InspArrange)
    (Label InspDirectionLabel) (CheckButton InspRowsAlongX) (Label InspPlaneLabel) (CheckButton InspUseZAxis)
    (Label InspGridLabel) (Label InspColumnsLabel) (InputPanel InspColumns) (Label InspGapLabel) (InputPanel InspGap)
    (Label InspValidation) (PushButton InspBuildButton)
    (ProgressBar InspProgress) (Label InspProgressText) (Label InspResultsTitle)
    (Table InspTable) (Label InspSummary) (Label InspDetails)
    (PushButton InspClearButton) (Label InspSpacer)
    (Label FooterStatus) (PushButton FooterCancelButton) (PushButton FullScreenButton)
    (PushButton ControlPanelButton) (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox v0.5.2 - Inspection Builder")
    (.Resizeable True) (.RememberSize True)
    (.TopOffset 8) (.BottomOffset 8) (.LeftOffset 8) (.RightOffset 8)
    (InspTitle.Label "Inspection Builder")
    (InspTitle.TopOffset 5) (InspTitle.BottomOffset 5) (InspTitle.LeftOffset 4)
    (InspDescription.Label "Batch assembly placement")
    (InspDescription.TopOffset 5) (InspDescription.BottomOffset 5) (InspDescription.LeftOffset 8)
    (InspTargetTitle.Label "TARGET")
    (InspTargetTitle.TopOffset 9) (InspTargetTitle.BottomOffset 5) (InspTargetTitle.LeftOffset 4)
    (InspActiveAsm.Label "No active assembly")
    (InspActiveAsm.TopOffset 9) (InspActiveAsm.BottomOffset 5) (InspActiveAsm.LeftOffset 8)
    (InspSourceTitle.Label "SOURCE")
    (InspSourceTitle.TopOffset 8) (InspSourceTitle.BottomOffset 5) (InspSourceTitle.LeftOffset 4)
    (InspFolderLabel.Label "Folder")
    (InspFolderLabel.TopOffset 4) (InspFolderLabel.BottomOffset 4) (InspFolderLabel.LeftOffset 4)
    (InspFolder.Columns 42)
    (InspFolder.TopOffset 4) (InspFolder.BottomOffset 4) (InspFolder.LeftOffset 4) (InspFolder.RightOffset 4)
    (InspBrowseButton.Label "Browse") (InspBrowseButton.ButtonStyle 3) (InspBrowseButton.HelpText "Choose a source folder")
    (InspBrowseButton.TopOffset 4) (InspBrowseButton.BottomOffset 4) (InspBrowseButton.LeftOffset 4) (InspBrowseButton.RightOffset 4)
    (InspDiscoveryLabel.Label "Folder options")
    (InspDiscoveryLabel.TopOffset 5) (InspDiscoveryLabel.BottomOffset 5) (InspDiscoveryLabel.LeftOffset 4)
    (InspRecursive.Label "Include subfolders")
    (InspRecursive.TopOffset 4) (InspRecursive.BottomOffset 4) (InspRecursive.LeftOffset 5) (InspRecursive.RightOffset 5)
    (InspLatest.Label "Latest only") (InspLatest.Set True)
    (InspLatest.TopOffset 4) (InspLatest.BottomOffset 4) (InspLatest.LeftOffset 5) (InspLatest.RightOffset 5)
    (InspTypesLabel.Label "Models")
    (InspTypesLabel.TopOffset 5) (InspTypesLabel.BottomOffset 5) (InspTypesLabel.LeftOffset 4)
    (InspParts.Label "Parts") (InspParts.Set True)
    (InspParts.TopOffset 4) (InspParts.BottomOffset 4) (InspParts.LeftOffset 5) (InspParts.RightOffset 5)
    (InspAssemblies.Label "Assemblies") (InspAssemblies.Set True)
    (InspAssemblies.TopOffset 4) (InspAssemblies.BottomOffset 4) (InspAssemblies.LeftOffset 5) (InspAssemblies.RightOffset 5)
    (InspStep.Label "STEP") (InspStep.Set True)
    (InspStep.TopOffset 4) (InspStep.BottomOffset 4) (InspStep.LeftOffset 5) (InspStep.RightOffset 5)
    (InspFamilyGroupLabel.Label "Family tables")
    (InspFamilyGroupLabel.TopOffset 5) (InspFamilyGroupLabel.BottomOffset 5) (InspFamilyGroupLabel.LeftOffset 4)
    (InspFamily.Label "Instances") (InspFamily.Set True)
    (InspFamily.TopOffset 4) (InspFamily.BottomOffset 4) (InspFamily.LeftOffset 5) (InspFamily.RightOffset 5)
    (InspGeneric.Label "Include generic")
    (InspGeneric.TopOffset 4) (InspGeneric.BottomOffset 4) (InspGeneric.LeftOffset 5) (InspGeneric.RightOffset 5)
    (InspFound.Label "Choose a source folder")
    (InspFound.TopOffset 5) (InspFound.BottomOffset 7) (InspFound.LeftOffset 4)
    (InspPlacementTitle.Label "PLACEMENT")
    (InspPlacementTitle.TopOffset 8) (InspPlacementTitle.BottomOffset 5) (InspPlacementTitle.LeftOffset 10)
    (InspArrangementLabel.Label "Mode")
    (InspArrangementLabel.TopOffset 5) (InspArrangementLabel.BottomOffset 5) (InspArrangementLabel.LeftOffset 10)
    (InspArrange.Label "Auto arrange") (InspArrange.Set True)
    (InspArrange.TopOffset 4) (InspArrange.BottomOffset 4) (InspArrange.LeftOffset 5) (InspArrange.RightOffset 5)
    (InspDirectionLabel.Label "Rows")
    (InspDirectionLabel.TopOffset 5) (InspDirectionLabel.BottomOffset 5) (InspDirectionLabel.LeftOffset 10)
    (InspRowsAlongX.Label "Along X (off = Y)")
    (InspRowsAlongX.TopOffset 4) (InspRowsAlongX.BottomOffset 4) (InspRowsAlongX.LeftOffset 5) (InspRowsAlongX.RightOffset 5)
    (InspPlaneLabel.Label "Plane")
    (InspPlaneLabel.TopOffset 5) (InspPlaneLabel.BottomOffset 5) (InspPlaneLabel.LeftOffset 8)
    (InspUseZAxis.Label "X-Z (off = X-Y)")
    (InspUseZAxis.TopOffset 4) (InspUseZAxis.BottomOffset 4) (InspUseZAxis.LeftOffset 5) (InspUseZAxis.RightOffset 5)
    (InspGridLabel.Label "Grid")
    (InspGridLabel.TopOffset 5) (InspGridLabel.BottomOffset 5) (InspGridLabel.LeftOffset 10)
    (InspColumnsLabel.Label "Columns") (InspColumnsLabel.TopOffset 5) (InspColumnsLabel.BottomOffset 5) (InspColumnsLabel.LeftOffset 5)
    (InspColumns.Columns 5)
    (InspColumns.TopOffset 4) (InspColumns.BottomOffset 4) (InspColumns.LeftOffset 4) (InspColumns.RightOffset 6)
    (InspGapLabel.Label "Gap") (InspGapLabel.TopOffset 5) (InspGapLabel.BottomOffset 5) (InspGapLabel.LeftOffset 6)
    (InspGap.Columns 8)
    (InspGap.TopOffset 4) (InspGap.BottomOffset 4) (InspGap.LeftOffset 4) (InspGap.RightOffset 4)
    (InspValidation.Label "")
    (InspValidation.TopOffset 5) (InspValidation.BottomOffset 7) (InspValidation.LeftOffset 10)
    (InspBuildButton.Label "Build assembly")
    (InspBuildButton.TopOffset 8) (InspBuildButton.BottomOffset 8) (InspBuildButton.LeftOffset 4) (InspBuildButton.RightOffset 6)
    (InspProgress.MinInteger 0) (InspProgress.MaxInteger 1) (InspProgress.Integer 0)
    (InspProgress.TopOffset 8) (InspProgress.BottomOffset 8) (InspProgress.LeftOffset 4) (InspProgress.RightOffset 4)
    (InspProgressText.Label "Ready")
    (InspProgressText.TopOffset 8) (InspProgressText.BottomOffset 8) (InspProgressText.LeftOffset 6)
    (InspResultsTitle.Label "RESULTS")
    (InspResultsTitle.TopOffset 10) (InspResultsTitle.BottomOffset 5) (InspResultsTitle.LeftOffset 4)
    (InspSummary.Label "No results")
    (InspSummary.TopOffset 10) (InspSummary.BottomOffset 5) (InspSummary.LeftOffset 8)
    (InspTable.RowNames "empty")
    (InspTable.ColumnNames "Source" "Kind" "AddedModel" "Status" "FeatureId")
    (InspTable.ColumnLabels "Source" "Kind" "Added model" "Status" "Feature")
    (InspTable.ColumnWidths 29 14 29 12 9) (InspTable.VisibleRows 13)
    (InspTable.ShowGrid True) (InspTable.AttachLeft True) (InspTable.AttachRight True)
    (InspTable.AttachTop True) (InspTable.AttachBottom True)
    (InspTable.TopOffset 5) (InspTable.BottomOffset 6) (InspTable.LeftOffset 4) (InspTable.RightOffset 4)
    (InspDetails.Label "Select a result for placement details.")
    (InspDetails.TopOffset 5) (InspDetails.BottomOffset 5) (InspDetails.LeftOffset 4)
    (InspClearButton.Label "Clear") (InspClearButton.ButtonStyle 3)
    (InspClearButton.TopOffset 4) (InspClearButton.BottomOffset 4) (InspClearButton.LeftOffset 4) (InspClearButton.RightOffset 4)
    (InspSpacer.Label "")
    (FooterStatus.Label "Ready")
    (FooterStatus.TopOffset 8) (FooterStatus.BottomOffset 2) (FooterStatus.LeftOffset 4)
    (FooterCancelButton.Label "Cancel")
    (FooterCancelButton.TopOffset 6) (FooterCancelButton.BottomOffset 2) (FooterCancelButton.LeftOffset 6)
    (FullScreenButton.Label "Maximize / restore") (FullScreenButton.ButtonStyle 3)
    (FullScreenButton.HelpText "Maximize or restore this tool window")
    (FullScreenButton.TopOffset 4) (FullScreenButton.BottomOffset 4) (FullScreenButton.LeftOffset 4) (FullScreenButton.RightOffset 4)
    (ControlPanelButton.Label "Toolbox") (ControlPanelButton.ButtonStyle 3)
    (ControlPanelButton.HelpText "Return to the Control Panel")
    (ControlPanelButton.TopOffset 4) (ControlPanelButton.BottomOffset 4) (ControlPanelButton.LeftOffset 4) (ControlPanelButton.RightOffset 4)
    (CloseButton.Label "") (CloseButton.Bitmap "cl_cancel")
    (CloseButton.HelpText "Close") (CloseButton.ButtonStyle 3)
    (CloseButton.TopOffset 4) (CloseButton.BottomOffset 4) (CloseButton.LeftOffset 4) (CloseButton.RightOffset 4)
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        (Grid (Rows 0 0 0 0 0 1 0 0) (Cols 1)
          (Grid (Rows 0) (Cols 0 0 1 0 0) ControlPanelButton InspTitle InspDescription FullScreenButton CloseButton)
          (Grid (Rows 0) (Cols 0 1) InspTargetTitle InspActiveAsm)
          (Grid (Rows 0) (Cols 1 1)
            (Grid (Rows 0 0 0 0 0 0) (Cols 1)
              InspSourceTitle
              (Grid (Rows 0) (Cols 0 1 0) InspFolderLabel InspFolder InspBrowseButton)
              (Grid (Rows 0) (Cols 0 0 0) InspDiscoveryLabel InspRecursive InspLatest)
              (Grid (Rows 0) (Cols 0 0 0 0) InspTypesLabel InspParts InspAssemblies InspStep)
              (Grid (Rows 0) (Cols 0 0 0) InspFamilyGroupLabel InspFamily InspGeneric)
              InspFound)
            (Grid (Rows 0 0 0 0 0) (Cols 1)
              InspPlacementTitle
              (Grid (Rows 0) (Cols 0 0) InspArrangementLabel InspArrange)
              (Grid (Rows 0) (Cols 0 0 0 0) InspDirectionLabel InspRowsAlongX InspPlaneLabel InspUseZAxis)
              (Grid (Rows 0) (Cols 0 0 0 0 0) InspGridLabel InspColumnsLabel InspColumns InspGapLabel InspGap)
              InspValidation))
          (Grid (Rows 0) (Cols 0 1 0) InspBuildButton InspProgress InspProgressText)
          (Grid (Rows 0) (Cols 0 1) InspResultsTitle InspSummary)
          InspTable
          InspDetails
          (Grid (Rows 0) (Cols 1 0) InspSpacer InspClearButton))
        (Grid (Rows 0) (Cols 1 0) FooterStatus FooterCancelButton)))))
