(Dialog aventics_weak
  (Components
    (Label WeakTitle) (Label WeakDescription) (Label WeakSourceTitle) (CheckButton WeakUseSelection)
    (Label WeakFolderLabel) (InputPanel WeakFolder) (PushButton WeakBrowseButton)
    (Label WeakOptionsTitle) (CheckButton WeakRecursive) (CheckButton WeakLatest) (Label WeakFound)
    (PushButton WeakRunButton) (ProgressBar WeakProgress) (Label WeakProgressText)
    (Label WeakResultsTitle) (Label WeakSearchLabel) (InputPanel WeakSearch) (CheckButton WeakIssuesOnly)
    (Table WeakTable) (Label WeakSummary) (Label WeakDetails)
    (PushButton WeakOpenButton) (PushButton WeakGotoButton) (PushButton WeakClearButton) (Label WeakSpacer)
    (Label FooterStatus) (PushButton FooterCancelButton) (PushButton FullScreenButton)
    (PushButton ControlPanelButton) (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox v0.5.0 - Weak Dimensions")
    (.Resizeable True) (.RememberSize True)
    (WeakTitle.Label "Weak dimensions")
    (WeakDescription.Label "Find weak section dimensions in selected parts or a folder.")
    (WeakSourceTitle.Label "Source")
    (WeakUseSelection.Label "Use Creo selection") (WeakUseSelection.Set True)
    (WeakFolderLabel.Label "Folder") (WeakFolder.Columns 58)
    (WeakBrowseButton.Label "Browse...")
    (WeakOptionsTitle.Label "Folder options")
    (WeakRecursive.Label "Include subfolders")
    (WeakLatest.Label "Latest version only") (WeakLatest.Set True)
    (WeakFound.Label "Selection mode: choose parts after starting the check.")
    (WeakRunButton.Label "Check dimensions")
    (WeakProgress.MinInteger 0) (WeakProgress.MaxInteger 1) (WeakProgress.Integer 0)
    (WeakProgressText.Label "Ready")
    (WeakResultsTitle.Label "Results") (WeakSearchLabel.Label "Search") (WeakSearch.Columns 28)
    (WeakIssuesOnly.Label "Issues only")
    (WeakTable.RowNames "empty")
    (WeakTable.ColumnNames "Part" "Status" "Feature" "Section" "Dimension")
    (WeakTable.ColumnLabels "Part" "Status" "Feature" "Section" "Weak dim")
    (WeakTable.ColumnWidths 25 11 28 9 11) (WeakTable.VisibleRows 12)
    (WeakTable.ShowGrid True) (WeakTable.AttachLeft True) (WeakTable.AttachRight True)
    (WeakTable.AttachTop True) (WeakTable.AttachBottom True)
    (WeakSummary.Label "No results")
    (WeakDetails.Label "Select a result to see its source and technical details.")
    (WeakOpenButton.Label "Open part") (WeakGotoButton.Label "Go to feature")
    (WeakClearButton.Label "Clear results") (WeakSpacer.Label "")
    (FooterStatus.Label "Ready") (FooterCancelButton.Label "Cancel operation")
    (FullScreenButton.Label "Full screen") (ControlPanelButton.Label "Control Panel") (CloseButton.Label "Close")
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        (Grid (Rows 0 0 0 0 0 0 0 0 0 1 0 0 0) (Cols 1)
          WeakTitle WeakDescription WeakSourceTitle WeakUseSelection
          (Grid (Rows 0) (Cols 0 1 0) WeakFolderLabel WeakFolder WeakBrowseButton)
          (Grid (Rows 0) (Cols 0 0 0 1) WeakOptionsTitle WeakRecursive WeakLatest WeakFound)
          (Grid (Rows 0) (Cols 0 1 0) WeakRunButton WeakProgress WeakProgressText)
          WeakResultsTitle
          (Grid (Rows 0) (Cols 0 0 1) WeakIssuesOnly WeakSearchLabel WeakSearch)
          WeakTable WeakSummary WeakDetails
          (Grid (Rows 0) (Cols 0 0 0 1) WeakOpenButton WeakGotoButton WeakClearButton WeakSpacer))
        (Grid (Rows 0) (Cols 1 0 0 0 0)
          FooterStatus FooterCancelButton FullScreenButton ControlPanelButton CloseButton)))))
