(Dialog aventics_inspection
  (Components
    (Label InspTitle) (Label InspDescription) (Label InspTargetTitle) (Label InspActiveAsm)
    (Label InspSourceTitle) (Label InspFolderLabel) (InputPanel InspFolder) (PushButton InspBrowseButton)
    (Label InspDiscoveryLabel) (CheckButton InspRecursive) (CheckButton InspLatest)
    (Label InspTypesLabel) (CheckButton InspParts) (CheckButton InspAssemblies) (CheckButton InspStep)
    (Label InspFamilyGroupLabel) (CheckButton InspFamily) (CheckButton InspGeneric) (Label InspFound)
    (Label InspPlacementTitle) (Label InspArrangementLabel) (CheckButton InspArrange)
    (Label InspDirectionLabel) (CheckButton InspRowsAlongX) (Label InspPlaneLabel) (CheckButton InspUseZAxis)
    (Label InspGridLabel) (Label InspColumnsLabel) (InputPanel InspColumns) (Label InspGapLabel) (InputPanel InspGap)
    (Label InspValidation) (PushButton InspBuildButton)
    (ProgressBar InspProgress) (Label InspProgressText) (Label InspResultsTitle)
    (Table InspTable) (Label InspSummary) (Label InspDetails)
    (PushButton InspClearButton) (Label InspSpacer)
    (Label FooterStatus) (PushButton FooterCancelButton) (PushButton FullScreenButton)
    (PushButton ControlPanelButton) (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox v0.5.0 - Inspection")
    (.Resizeable True) (.RememberSize True)
    (InspTitle.Label "Inspection assembly builder")
    (InspDescription.Label "Add discovered models without constraints.")
    (InspTargetTitle.Label "Target assembly") (InspActiveAsm.Label "No active assembly")
    (InspSourceTitle.Label "Source") (InspFolderLabel.Label "Folder")
    (InspFolder.Columns 58) (InspBrowseButton.Label "Browse...")
    (InspDiscoveryLabel.Label "Discovery")
    (InspRecursive.Label "Include subfolders")
    (InspLatest.Label "Latest version only") (InspLatest.Set True)
    (InspTypesLabel.Label "Types")
    (InspParts.Label "Parts") (InspParts.Set True)
    (InspAssemblies.Label "Assemblies") (InspAssemblies.Set True)
    (InspStep.Label "STEP") (InspStep.Set True)
    (InspFamilyGroupLabel.Label "Family table")
    (InspFamily.Label "Instances") (InspFamily.Set True)
    (InspGeneric.Label "Also generic")
    (InspFound.Label "Choose a folder to discover eligible source files.")
    (InspPlacementTitle.Label "Placement")
    (InspArrangementLabel.Label "Arrangement")
    (InspArrange.Label "Auto arrange (off = same origin)") (InspArrange.Set True)
    (InspDirectionLabel.Label "Row direction")
    (InspRowsAlongX.Label "Rows along X")
    (InspPlaneLabel.Label "Plane")
    (InspUseZAxis.Label "X-Z (off = X-Y)")
    (InspGridLabel.Label "Grid")
    (InspColumnsLabel.Label "Columns") (InspColumns.Columns 5)
    (InspGapLabel.Label "Gap (assembly units)") (InspGap.Columns 8)
    (InspValidation.Label "") (InspBuildButton.Label "Add to assembly")
    (InspProgress.MinInteger 0) (InspProgress.MaxInteger 1) (InspProgress.Integer 0)
    (InspProgressText.Label "Ready") (InspResultsTitle.Label "Results")
    (InspTable.RowNames "empty")
    (InspTable.ColumnNames "Source" "Kind" "AddedModel" "Status" "FeatureId")
    (InspTable.ColumnLabels "Source" "Kind" "Added model" "Status" "Feature ID")
    (InspTable.ColumnWidths 27 15 27 12 11) (InspTable.VisibleRows 10)
    (InspTable.ShowGrid True) (InspTable.AttachLeft True) (InspTable.AttachRight True)
    (InspTable.AttachTop True) (InspTable.AttachBottom True)
    (InspSummary.Label "No results")
    (InspDetails.Label "Select a result to see its source and technical details.")
    (InspClearButton.Label "Clear results") (InspSpacer.Label "")
    (FooterStatus.Label "Ready") (FooterCancelButton.Label "Cancel operation")
    (FullScreenButton.Label "Full screen") (ControlPanelButton.Label "Control Panel") (CloseButton.Label "Close")
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        (Grid (Rows 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0) (Cols 1)
          InspTitle InspDescription InspTargetTitle InspActiveAsm InspSourceTitle
          (Grid (Rows 0) (Cols 0 1 0) InspFolderLabel InspFolder InspBrowseButton)
          (Grid (Rows 0) (Cols 0 0 0) InspDiscoveryLabel InspRecursive InspLatest)
          (Grid (Rows 0) (Cols 0 0 0 0) InspTypesLabel InspParts InspAssemblies InspStep)
          (Grid (Rows 0) (Cols 0 0 0 1) InspFamilyGroupLabel InspFamily InspGeneric InspFound)
          InspPlacementTitle
          (Grid (Rows 0) (Cols 0 0) InspArrangementLabel InspArrange)
          (Grid (Rows 0) (Cols 0 0) InspDirectionLabel InspRowsAlongX)
          (Grid (Rows 0) (Cols 0 0) InspPlaneLabel InspUseZAxis)
          (Grid (Rows 0) (Cols 0 0 0 0 0 1) InspGridLabel InspColumnsLabel InspColumns InspGapLabel InspGap InspValidation)
          (Grid (Rows 0) (Cols 0 1 0) InspBuildButton InspProgress InspProgressText)
          InspResultsTitle InspTable InspSummary InspDetails
          (Grid (Rows 0) (Cols 0 1) InspClearButton InspSpacer))
        (Grid (Rows 0) (Cols 1 0 0 0 0)
          FooterStatus FooterCancelButton FullScreenButton ControlPanelButton CloseButton)))))
