(Dialog aventics_toolbox
  (Components
    (Tab ToolTabs OverviewLayout WeakLayout AccuracyLayout InspectionLayout InstanceBuilderLayout)
    (Label FooterStatus)
    (PushButton FooterCancelButton)
    (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox - v0.4.0")
    (.Resizeable True) (.RememberSize True)
    (ToolTabs.Decorated True)
    (ToolTabs.AttachLeft True) (ToolTabs.AttachRight True)
    (ToolTabs.AttachTop True) (ToolTabs.AttachBottom True)
    (ToolTabs.LeftOffset 8) (ToolTabs.RightOffset 8)
    (ToolTabs.TopOffset 8) (ToolTabs.BottomOffset 8)
    (FooterStatus.Label "Ready")
    (FooterCancelButton.Label "Cancel operation")
    (CloseButton.Label "Close")
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        ToolTabs
        (Grid (Rows 0) (Cols 1 0 0) FooterStatus FooterCancelButton CloseButton)))))

(Layout OverviewLayout
  (Components
    (Label OverviewTitle) (Label OverviewIntro)
    (Label OverviewQcTitle) (Label OverviewQcDesc)
    (PushButton OverviewRunAllButton) (Label OverviewRunAllStatus)
    (PushButton OverviewWeakButton) (PushButton OverviewAccButton)
    (Label OverviewAssemblyTitle) (Label OverviewAssemblyDesc)
    (PushButton OverviewInspButton) (PushButton OverviewInstButton)
    (Label OverviewSafety) (Label OverviewSpacer))
  (Resources
    (.Label "Overview")
    (OverviewTitle.Label "Aventics Toolbox")
    (OverviewIntro.Label "Quality-control and assembly utilities for Creo Parametric.")
    (OverviewQcTitle.Label "Quality control - read-only")
    (OverviewQcDesc.Label "Check selected parts and assemblies. Weak Dimensions applies to parts; Accuracy applies to both.")
    (OverviewRunAllButton.Label "Run all QC on Creo selection")
    (OverviewRunAllStatus.Label "Ready. Results appear in the Weak Dimensions and Accuracy tabs.")
    (OverviewWeakButton.Label "Open Weak Dimensions")
    (OverviewAccButton.Label "Open Accuracy")
    (OverviewAssemblyTitle.Label "Assembly tools")
    (OverviewAssemblyDesc.Label "Inspection and Instance Builder add unconstrained components to the active assembly.")
    (OverviewInspButton.Label "Open Inspection")
    (OverviewInstButton.Label "Open Instance Builder")
    (OverviewSafety.Label "Assembly tools never save the active assembly automatically.")
    (OverviewSpacer.Label "")
    (.Decorated False)
    (.TopOffset 12) (.BottomOffset 12) (.LeftOffset 12) (.RightOffset 12)
    (.Layout
      (Grid (Rows 0 0 0 0 0 0 0 0 0 0 1) (Cols 1)
        OverviewTitle OverviewIntro OverviewQcTitle OverviewQcDesc
        OverviewRunAllButton OverviewRunAllStatus
        (Grid (Rows 0) (Cols 0 0 1) OverviewWeakButton OverviewAccButton OverviewSpacer)
        OverviewAssemblyTitle OverviewAssemblyDesc
        (Grid (Rows 0) (Cols 0 0 1) OverviewInspButton OverviewInstButton OverviewSpacer)
        OverviewSafety))))

(Layout WeakLayout
  (Components
    (Label WeakTitle) (Label WeakDescription) (Label WeakSourceTitle) (CheckButton WeakUseSelection)
    (Label WeakFolderLabel) (InputPanel WeakFolder) (PushButton WeakBrowseButton)
    (Label WeakOptionsTitle) (CheckButton WeakRecursive) (CheckButton WeakLatest) (Label WeakFound)
    (PushButton WeakRunButton) (ProgressBar WeakProgress) (Label WeakProgressText)
    (Label WeakResultsTitle) (Label WeakSearchLabel) (InputPanel WeakSearch) (CheckButton WeakIssuesOnly)
    (Table WeakTable) (Label WeakSummary) (Label WeakDetails)
    (PushButton WeakOpenButton) (PushButton WeakGotoButton) (PushButton WeakClearButton)
    (Label WeakSpacer))
  (Resources
    (.Label "Weak Dimensions")
    (WeakTitle.Label "Weak dimensions")
    (WeakDescription.Label "Find weak section dimensions in selected parts or a folder.")
    (WeakSourceTitle.Label "Source")
    (WeakUseSelection.Label "Use Creo selection") (WeakUseSelection.Set True)
    (WeakFolderLabel.Label "Folder") (WeakFolder.Columns 58)
    (WeakBrowseButton.Label "Browse...")
    (WeakOptionsTitle.Label "Folder options")
    (WeakRecursive.Label "Include subfolders")
    (WeakLatest.Label "Latest version only") (WeakLatest.Set True)
    (WeakFound.Label "Selection mode: choose parts after starting the check.")
    (WeakRunButton.Label "Check dimensions")
    (WeakProgress.MinInteger 0) (WeakProgress.MaxInteger 1) (WeakProgress.Integer 0)
    (WeakProgressText.Label "Ready")
    (WeakResultsTitle.Label "Results") (WeakSearchLabel.Label "Search") (WeakSearch.Columns 28)
    (WeakIssuesOnly.Label "Issues only")
    (WeakTable.RowNames "empty")
    (WeakTable.ColumnNames "Part" "Status" "Feature" "Section" "Dimension")
    (WeakTable.ColumnLabels "Part" "Status" "Feature" "Section" "Weak dim")
    (WeakTable.ColumnWidths 25 11 28 9 11) (WeakTable.VisibleRows 12)
    (WeakTable.ShowGrid True) (WeakTable.AttachLeft True) (WeakTable.AttachRight True)
    (WeakTable.AttachTop True) (WeakTable.AttachBottom True)
    (WeakSummary.Label "No results")
    (WeakDetails.Label "Select a result to see its source and technical details.")
    (WeakOpenButton.Label "Open part") (WeakGotoButton.Label "Go to feature")
    (WeakClearButton.Label "Clear results") (WeakSpacer.Label "")
    (.Decorated False)
    (.TopOffset 8) (.BottomOffset 8) (.LeftOffset 8) (.RightOffset 8)
    (.Layout
      (Grid (Rows 0 0 0 0 0 0 0 0 0 1 0 0 0) (Cols 1)
        WeakTitle WeakDescription WeakSourceTitle WeakUseSelection
        (Grid (Rows 0) (Cols 0 1 0) WeakFolderLabel WeakFolder WeakBrowseButton)
        (Grid (Rows 0) (Cols 0 0 0 1) WeakOptionsTitle WeakRecursive WeakLatest WeakFound)
        (Grid (Rows 0) (Cols 0 1 0) WeakRunButton WeakProgress WeakProgressText)
        WeakResultsTitle
        (Grid (Rows 0) (Cols 0 0 1) WeakIssuesOnly WeakSearchLabel WeakSearch)
        WeakTable WeakSummary WeakDetails
        (Grid (Rows 0) (Cols 0 0 0 1) WeakOpenButton WeakGotoButton WeakClearButton WeakSpacer)))))

(Layout AccuracyLayout
  (Components
    (Label AccTitle) (Label AccRule) (Label AccSourceTitle) (CheckButton AccUseSelection)
    (Label AccFolderLabel) (InputPanel AccFolder) (PushButton AccBrowseButton)
    (Label AccOptionsTitle) (CheckButton AccRecursive) (CheckButton AccLatest)
    (Label AccTypesTitle) (CheckButton AccParts) (CheckButton AccAssemblies) (Label AccFound)
    (PushButton AccRunButton) (ProgressBar AccProgress) (Label AccProgressText)
    (Label AccResultsTitle) (Label AccSearchLabel) (InputPanel AccSearch) (CheckButton AccIssuesOnly)
    (Table AccTable) (Label AccSummary) (Label AccDetails)
    (PushButton AccOpenButton) (PushButton AccClearButton) (Label AccSpacer))
  (Resources
    (.Label "Accuracy")
    (AccTitle.Label "Model accuracy")
    (AccRule.Label "Required: ABSOLUTE = 0.001")
    (AccSourceTitle.Label "Source")
    (AccUseSelection.Label "Use Creo selection") (AccUseSelection.Set True)
    (AccFolderLabel.Label "Folder") (AccFolder.Columns 58)
    (AccBrowseButton.Label "Browse...")
    (AccOptionsTitle.Label "Folder options")
    (AccRecursive.Label "Include subfolders")
    (AccLatest.Label "Latest version only") (AccLatest.Set True)
    (AccTypesTitle.Label "Model types")
    (AccParts.Label "Parts") (AccParts.Set True)
    (AccAssemblies.Label "Assemblies") (AccAssemblies.Set True)
    (AccFound.Label "Selection mode: choose models after starting the check.")
    (AccRunButton.Label "Check accuracy")
    (AccProgress.MinInteger 0) (AccProgress.MaxInteger 1) (AccProgress.Integer 0)
    (AccProgressText.Label "Ready")
    (AccResultsTitle.Label "Results") (AccSearchLabel.Label "Search") (AccSearch.Columns 28)
    (AccIssuesOnly.Label "Issues only")
    (AccTable.RowNames "empty")
    (AccTable.ColumnNames "Model" "Kind" "AccuracyType" "Accuracy" "Status")
    (AccTable.ColumnLabels "Model" "Kind" "Accuracy type" "Accuracy" "Status")
    (AccTable.ColumnWidths 28 12 16 13 11) (AccTable.VisibleRows 12)
    (AccTable.ShowGrid True) (AccTable.AttachLeft True) (AccTable.AttachRight True)
    (AccTable.AttachTop True) (AccTable.AttachBottom True)
    (AccSummary.Label "No results")
    (AccDetails.Label "Select a result to see its source and technical details.")
    (AccOpenButton.Label "Open model") (AccClearButton.Label "Clear results")
    (AccSpacer.Label "")
    (.Decorated False)
    (.TopOffset 8) (.BottomOffset 8) (.LeftOffset 8) (.RightOffset 8)
    (.Layout
      (Grid (Rows 0 0 0 0 0 0 0 0 0 1 0 0 0) (Cols 1)
        AccTitle AccRule AccSourceTitle AccUseSelection
        (Grid (Rows 0) (Cols 0 1 0) AccFolderLabel AccFolder AccBrowseButton)
        (Grid (Rows 0) (Cols 0 0 0 1) AccOptionsTitle AccRecursive AccLatest AccFound)
        (Grid (Rows 0) (Cols 0 0 0 1) AccTypesTitle AccParts AccAssemblies AccSpacer)
        (Grid (Rows 0) (Cols 0 1 0) AccRunButton AccProgress AccProgressText)
        AccResultsTitle
        (Grid (Rows 0) (Cols 0 0 1) AccIssuesOnly AccSearchLabel AccSearch)
        AccTable AccSummary AccDetails
        (Grid (Rows 0) (Cols 0 0 1) AccOpenButton AccClearButton AccSpacer)))))

(Layout InspectionLayout
  (Components
    (Label InspTitle) (Label InspDescription) (Label InspTargetTitle) (Label InspActiveAsm)
    (Label InspSourceTitle) (Label InspFolderLabel) (InputPanel InspFolder) (PushButton InspBrowseButton)
    (Label InspDiscoveryLabel) (CheckButton InspRecursive) (CheckButton InspLatest)
    (Label InspTypesLabel) (CheckButton InspParts) (CheckButton InspAssemblies) (CheckButton InspStep)
    (Label InspFamilyGroupLabel) (CheckButton InspFamily) (CheckButton InspGeneric) (Label InspFound)
    (Label InspPlacementTitle) (Label InspArrangementLabel) (CheckButton InspArrange)
    (Label InspDirectionLabel) (CheckButton InspRowsAlongX) (Label InspPlaneLabel) (CheckButton InspUseZAxis)
    (Label InspGridLabel) (Label InspColumnsLabel) (InputPanel InspColumns) (Label InspGapLabel) (InputPanel InspGap)
    (Label InspValidation) (PushButton InspBuildButton)
    (ProgressBar InspProgress) (Label InspProgressText) (Label InspResultsTitle)
    (Table InspTable) (Label InspSummary) (Label InspDetails)
    (PushButton InspClearButton) (Label InspSpacer))
  (Resources
    (.Label "Inspection")
    (InspTitle.Label "Inspection assembly builder")
    (InspDescription.Label "Add discovered models without constraints.")
    (InspTargetTitle.Label "Target assembly") (InspActiveAsm.Label "No active assembly")
    (InspSourceTitle.Label "Source") (InspFolderLabel.Label "Folder")
    (InspFolder.Columns 58) (InspBrowseButton.Label "Browse...")
    (InspDiscoveryLabel.Label "Discovery")
    (InspRecursive.Label "Include subfolders")
    (InspLatest.Label "Latest version only") (InspLatest.Set True)
    (InspTypesLabel.Label "Types")
    (InspParts.Label "Parts") (InspParts.Set True)
    (InspAssemblies.Label "Assemblies") (InspAssemblies.Set True)
    (InspStep.Label "STEP") (InspStep.Set True)
    (InspFamilyGroupLabel.Label "Family table")
    (InspFamily.Label "Instances") (InspFamily.Set True)
    (InspGeneric.Label "Also generic")
    (InspFound.Label "Choose a folder to discover eligible source files.")
    (InspPlacementTitle.Label "Placement")
    (InspArrangementLabel.Label "Arrangement")
    (InspArrange.Label "Auto arrange (off = same origin)") (InspArrange.Set True)
    (InspDirectionLabel.Label "Row direction")
    (InspRowsAlongX.Label "Rows along X")
    (InspPlaneLabel.Label "Plane")
    (InspUseZAxis.Label "X-Z (off = X-Y)")
    (InspGridLabel.Label "Grid")
    (InspColumnsLabel.Label "Columns") (InspColumns.Columns 5)
    (InspGapLabel.Label "Gap (assembly units)") (InspGap.Columns 8)
    (InspValidation.Label "") (InspBuildButton.Label "Add to assembly")
    (InspProgress.MinInteger 0) (InspProgress.MaxInteger 1) (InspProgress.Integer 0)
    (InspProgressText.Label "Ready") (InspResultsTitle.Label "Results")
    (InspTable.RowNames "empty")
    (InspTable.ColumnNames "Source" "Kind" "AddedModel" "Status" "FeatureId")
    (InspTable.ColumnLabels "Source" "Kind" "Added model" "Status" "Feature ID")
    (InspTable.ColumnWidths 27 15 27 12 11) (InspTable.VisibleRows 10)
    (InspTable.ShowGrid True) (InspTable.AttachLeft True) (InspTable.AttachRight True)
    (InspTable.AttachTop True) (InspTable.AttachBottom True)
    (InspSummary.Label "No results")
    (InspDetails.Label "Select a result to see its source and technical details.")
    (InspClearButton.Label "Clear results") (InspSpacer.Label "")
    (.Decorated False)
    (.TopOffset 8) (.BottomOffset 8) (.LeftOffset 8) (.RightOffset 8)
    (.Layout
      (Grid (Rows 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0) (Cols 1)
        InspTitle InspDescription InspTargetTitle InspActiveAsm InspSourceTitle
        (Grid (Rows 0) (Cols 0 1 0) InspFolderLabel InspFolder InspBrowseButton)
        (Grid (Rows 0) (Cols 0 0 0 1) InspDiscoveryLabel InspRecursive InspLatest InspSpacer)
        (Grid (Rows 0) (Cols 0 0 0 0 1) InspTypesLabel InspParts InspAssemblies InspStep InspSpacer)
        (Grid (Rows 0) (Cols 0 0 0 1) InspFamilyGroupLabel InspFamily InspGeneric InspFound)
        InspPlacementTitle
        (Grid (Rows 0) (Cols 0 0 0 0 1) InspArrangementLabel InspArrange InspDirectionLabel InspRowsAlongX InspSpacer)
        (Grid (Rows 0) (Cols 0 0 0 1) InspPlaneLabel InspUseZAxis InspGridLabel InspSpacer)
        (Grid (Rows 0) (Cols 0 0 0 0 0 1) InspColumnsLabel InspColumns InspGapLabel InspGap InspValidation InspSpacer)
        (Grid (Rows 0) (Cols 0 1 0) InspBuildButton InspProgress InspProgressText)
        InspResultsTitle InspTable InspSummary InspDetails
        (Grid (Rows 0) (Cols 0 1) InspClearButton InspSpacer)))))

(Layout InstanceBuilderLayout
  (Components
    (Label InstTitle) (Label InstDescription) (Label InstTargetTitle) (Label InstActiveAsm)
    (Label InstInputTitle) (Label InstSourceTitle) (Label InstFolderLabel) (InputPanel InstFolder) (PushButton InstBrowseButton)
    (CheckButton InstRecursive) (CheckButton InstLatest) (Label InstFound)
    (Label InstCodesTitle) (TextArea InstCodes) (Label InstCodesHelp)
    (Label InstPlanTitle) (Label InstColumnsLabel) (InputPanel InstColumns)
    (Label InstGapLabel) (InputPanel InstGap) (PushButton InstPlanButton) (Label InstValidation)
    (Label InstBuildReviewTitle) (PushButton InstBuildButton) (ProgressBar InstProgress) (Label InstProgressText)
    (Label InstResultsTitle) (CheckButton InstUnresolvedOnly) (Table InstTable) (Label InstSummary) (Label InstDetails)
    (PushButton InstExportButton) (PushButton InstClearButton) (Label InstSpacer))
  (Resources
    (.Label "Instance Builder")
    (InstTitle.Label "Instance builder")
    (InstDescription.Label "Resolve requested codes and add matching models to the active assembly.")
    (InstTargetTitle.Label "Target assembly") (InstActiveAsm.Label "No active assembly")
    (InstInputTitle.Label "1. Input")
    (InstSourceTitle.Label "Search source") (InstFolderLabel.Label "Folder")
    (InstFolder.Columns 58) (InstBrowseButton.Label "Browse...")
    (InstRecursive.Label "Include subfolders")
    (InstLatest.Label "Latest version only") (InstLatest.Set True)
    (InstFound.Label "Choose the folder containing Creo parts and assemblies to search.")
    (InstCodesTitle.Label "Requested codes")
    (InstCodes.Rows 6) (InstCodes.Columns 64) (InstCodes.MinRows 4)
    (InstCodes.AttachLeft True) (InstCodes.AttachRight True)
    (InstCodesHelp.Label "One per line; comma, semicolon, and tab are also accepted.")
    (InstPlanTitle.Label "2. Plan")
    (InstColumnsLabel.Label "Columns") (InstColumns.Columns 5)
    (InstGapLabel.Label "Gap (assembly units)") (InstGap.Columns 8)
    (InstPlanButton.Label "Plan positions")
    (InstValidation.Label "")
    (InstBuildReviewTitle.Label "3. Build and review")
    (InstBuildButton.Label "Find and add instances")
    (InstProgress.MinInteger 0) (InstProgress.MaxInteger 1) (InstProgress.Integer 0)
    (InstProgressText.Label "Ready")
    (InstResultsTitle.Label "Results")
    (InstUnresolvedOnly.Label "Unresolved only")
    (InstTable.RowNames "empty")
    (InstTable.ColumnNames "Code" "Row" "Column" "Generic" "AddedModel" "Status")
    (InstTable.ColumnLabels "Requested code" "Row" "Column" "Generic" "Added model" "Status")
    (InstTable.ColumnWidths 24 7 7 24 25 12) (InstTable.VisibleRows 10)
    (InstTable.ShowGrid True) (InstTable.AttachLeft True) (InstTable.AttachRight True)
    (InstTable.AttachTop True) (InstTable.AttachBottom True)
    (InstSummary.Label "No plan")
    (InstDetails.Label "Plan positions first, then build. Missing codes keep their allocated cells empty.")
    (InstExportButton.Label "Export CSV report")
    (InstClearButton.Label "Clear results") (InstSpacer.Label "")
    (.Decorated False)
    (.TopOffset 8) (.BottomOffset 8) (.LeftOffset 8) (.RightOffset 8)
    (.Layout
      (Grid (Rows 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0) (Cols 1)
        InstTitle InstDescription InstTargetTitle InstActiveAsm InstInputTitle
        (Grid (Rows 0) (Cols 0 1 0) InstFolderLabel InstFolder InstBrowseButton)
        (Grid (Rows 0) (Cols 0 0 1) InstRecursive InstLatest InstFound)
        InstCodesTitle InstCodes InstCodesHelp InstPlanTitle
        (Grid (Rows 0) (Cols 0 0 0 0 0 1) InstColumnsLabel InstColumns InstGapLabel InstGap InstPlanButton InstValidation)
        InstBuildReviewTitle
        (Grid (Rows 0) (Cols 0 1 0) InstBuildButton InstProgress InstProgressText)
        (Grid (Rows 0) (Cols 0 0 1) InstResultsTitle InstUnresolvedOnly InstSpacer)
        InstTable InstSummary InstDetails
        (Grid (Rows 0) (Cols 0 0 1) InstExportButton InstClearButton InstSpacer)))))
