(Dialog aventics_accuracy
  (Components
    (Label AccTitle) (Label AccRule) (Label AccSourceTitle) (CheckButton AccUseSelection)
    (Label AccFolderLabel) (InputPanel AccFolder) (PushButton AccBrowseButton)
    (Label AccOptionsTitle) (CheckButton AccRecursive) (CheckButton AccLatest)
    (Label AccTypesTitle) (CheckButton AccParts) (CheckButton AccAssemblies) (Label AccFound)
    (PushButton AccRunButton) (ProgressBar AccProgress) (Label AccProgressText)
    (Label AccResultsTitle) (Label AccSearchLabel) (InputPanel AccSearch) (CheckButton AccIssuesOnly)
    (Table AccTable) (Label AccSummary) (Label AccDetails)
    (PushButton AccOpenButton) (PushButton AccClearButton) (Label AccSpacer)
    (Label FooterStatus) (PushButton FooterCancelButton) (PushButton FullScreenButton)
    (PushButton ControlPanelButton) (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox v0.5.2 - Accuracy")
    (.Resizeable True) (.RememberSize True)
    (AccTitle.Label "Accuracy")
    (AccRule.Label "Requirement: ABSOLUTE = 0.001")
    (AccSourceTitle.Label "SOURCE")
    (AccUseSelection.Label "Use selected models") (AccUseSelection.Set True)
    (AccFolderLabel.Label "Folder") (AccFolder.Columns 52)
    (AccBrowseButton.Label "Browse")
    (AccOptionsTitle.Label "Folder options")
    (AccRecursive.Label "Include subfolders")
    (AccLatest.Label "Latest only") (AccLatest.Set True)
    (AccTypesTitle.Label "MODEL TYPES")
    (AccParts.Label "Parts") (AccParts.Set True)
    (AccAssemblies.Label "Assemblies") (AccAssemblies.Set True)
    (AccFound.Label "Using selected models")
    (AccRunButton.Label "Check")
    (AccProgress.MinInteger 0) (AccProgress.MaxInteger 1) (AccProgress.Integer 0)
    (AccProgressText.Label "Ready")
    (AccResultsTitle.Label "RESULTS") (AccSearchLabel.Label "Search") (AccSearch.Columns 26)
    (AccIssuesOnly.Label "Issues only")
    (AccTable.RowNames "empty")
    (AccTable.ColumnNames "Model" "Kind" "AccuracyType" "Accuracy" "Status")
    (AccTable.ColumnLabels "Model" "Kind" "Type" "Accuracy" "Status")
    (AccTable.ColumnWidths 30 12 13 13 11) (AccTable.VisibleRows 15)
    (AccTable.ShowGrid True) (AccTable.AttachLeft True) (AccTable.AttachRight True)
    (AccTable.AttachTop True) (AccTable.AttachBottom True)
    (AccSummary.Label "No results")
    (AccDetails.Label "Select a result for source and technical details.")
    (AccOpenButton.Label "Open") (AccClearButton.Label "Clear") (AccSpacer.Label "")
    (FooterStatus.Label "Ready") (FooterCancelButton.Label "Cancel")
    (FullScreenButton.Label "Maximize / restore") (ControlPanelButton.Label "Toolbox") (CloseButton.Label "Close")
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        (Grid (Rows 0 0 0 0 0 0 1 0 0) (Cols 1)
          (Grid (Rows 0) (Cols 0 0 1 0 0) ControlPanelButton AccTitle AccRule FullScreenButton CloseButton)
          (Grid (Rows 0) (Cols 0 0 0 1 0) AccSourceTitle AccUseSelection AccFolderLabel AccFolder AccBrowseButton)
          (Grid (Rows 0) (Cols 0 0 0 1) AccOptionsTitle AccRecursive AccLatest AccFound)
          (Grid (Rows 0) (Cols 0 0 0) AccTypesTitle AccParts AccAssemblies)
          (Grid (Rows 0) (Cols 0 1 0) AccRunButton AccProgress AccProgressText)
          (Grid (Rows 0) (Cols 0 1 0 0 0) AccResultsTitle AccSummary AccIssuesOnly AccSearchLabel AccSearch)
          AccTable
          AccDetails
          (Grid (Rows 0) (Cols 0 1 0) AccOpenButton AccSpacer AccClearButton))
        (Grid (Rows 0) (Cols 1 0) FooterStatus FooterCancelButton)))))
