(Dialog aventics_accuracy
  (Components
    (Label AccTitle) (Label AccRule) (Label AccSourceTitle) (CheckButton AccUseSelection)
    (Label AccFolderLabel) (InputPanel AccFolder) (PushButton AccBrowseButton)
    (Label AccOptionsTitle) (CheckButton AccRecursive) (CheckButton AccLatest)
    (Label AccTypesTitle) (CheckButton AccParts) (CheckButton AccAssemblies) (Label AccFound)
    (PushButton AccRunButton) (ProgressBar AccProgress) (Label AccProgressText)
    (Label AccResultsTitle) (Label AccSearchLabel) (InputPanel AccSearch) (CheckButton AccIssuesOnly)
    (Table AccTable) (Label AccSummary) (Label AccDetails)
    (PushButton AccOpenButton) (PushButton AccClearButton) (Label AccSpacer)
    (Label FooterStatus) (PushButton FooterCancelButton) (PushButton FullScreenButton)
    (PushButton ControlPanelButton) (PushButton CloseButton))
  (Resources
    (.Label "Aventics Toolbox v0.5.0 - Accuracy")
    (.Resizeable True) (.RememberSize True)
    (AccTitle.Label "Model accuracy")
    (AccRule.Label "Required: ABSOLUTE = 0.001")
    (AccSourceTitle.Label "Source")
    (AccUseSelection.Label "Use Creo selection") (AccUseSelection.Set True)
    (AccFolderLabel.Label "Folder") (AccFolder.Columns 58)
    (AccBrowseButton.Label "Browse...")
    (AccOptionsTitle.Label "Folder options")
    (AccRecursive.Label "Include subfolders")
    (AccLatest.Label "Latest version only") (AccLatest.Set True)
    (AccTypesTitle.Label "Model types")
    (AccParts.Label "Parts") (AccParts.Set True)
    (AccAssemblies.Label "Assemblies") (AccAssemblies.Set True)
    (AccFound.Label "Selection mode: choose models after starting the check.")
    (AccRunButton.Label "Check accuracy")
    (AccProgress.MinInteger 0) (AccProgress.MaxInteger 1) (AccProgress.Integer 0)
    (AccProgressText.Label "Ready")
    (AccResultsTitle.Label "Results") (AccSearchLabel.Label "Search") (AccSearch.Columns 28)
    (AccIssuesOnly.Label "Issues only")
    (AccTable.RowNames "empty")
    (AccTable.ColumnNames "Model" "Kind" "AccuracyType" "Accuracy" "Status")
    (AccTable.ColumnLabels "Model" "Kind" "Accuracy type" "Accuracy" "Status")
    (AccTable.ColumnWidths 28 12 16 13 11) (AccTable.VisibleRows 12)
    (AccTable.ShowGrid True) (AccTable.AttachLeft True) (AccTable.AttachRight True)
    (AccTable.AttachTop True) (AccTable.AttachBottom True)
    (AccSummary.Label "No results")
    (AccDetails.Label "Select a result to see its source and technical details.")
    (AccOpenButton.Label "Open model") (AccClearButton.Label "Clear results") (AccSpacer.Label "")
    (FooterStatus.Label "Ready") (FooterCancelButton.Label "Cancel operation")
    (FullScreenButton.Label "Full screen") (ControlPanelButton.Label "Control Panel") (CloseButton.Label "Close")
    (.Layout
      (Grid (Rows 1 0) (Cols 1)
        (Grid (Rows 0 0 0 0 0 0 0 0 0 0 1 0 0 0) (Cols 1)
          AccTitle AccRule AccSourceTitle AccUseSelection
          (Grid (Rows 0) (Cols 0 1 0) AccFolderLabel AccFolder AccBrowseButton)
          (Grid (Rows 0) (Cols 0 0 0 1) AccOptionsTitle AccRecursive AccLatest AccFound)
          (Grid (Rows 0) (Cols 0 0 0) AccTypesTitle AccParts AccAssemblies)
          (Grid (Rows 0) (Cols 0 1 0) AccRunButton AccProgress AccProgressText)
          AccResultsTitle
          (Grid (Rows 0) (Cols 0 0 1) AccIssuesOnly AccSearchLabel AccSearch)
          AccTable AccSummary AccDetails
          (Grid (Rows 0) (Cols 0 0 1) AccOpenButton AccClearButton AccSpacer))
        (Grid (Rows 0) (Cols 1 0 0 0 0)
          FooterStatus FooterCancelButton FullScreenButton ControlPanelButton CloseButton)))))
